---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pv-claim
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-log-pv-claim
spec:
  storageClassName: nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
