apiVersion: v2
name: docspace
kubeVersion: ">= 1.19.0-0"
description: ONLYOFFICE Apps is a secure, room-based DMS featuring advanced document editors and AI agents.
type: application
keywords:
  - dms
  - rooms
  - onlyoffice
  - collaboration
  - productivity
  - document-management
  - communication
home: https://onlyoffice.com
sources:
  - https://github.com/ONLYOFFICE
  - https://github.com/ONLYOFFICE/DocSpace
  - https://github.com/ONLYOFFICE/DocSpace-server
dependencies:
- name: docs
  version: 6.1.1
  repository: https://download.onlyoffice.com/charts/stable
  condition: docs.enabled
icon: https://avatars.githubusercontent.com/u/1426033
version: 4.0.0
appVersion: 4.0.0
