# Default values for appserver

## Appserver common parameters
## This block defines common parameters for all deployments and statefulsets

connections:
  envExtension: "none"
  mysqlDatabaseMigration: "true"
  mysqlHost: "mysql"
  mysqlDatabase: "onlyoffice"
  mysqlUser: "onlyoffice_user"
  mysqlPassword: ""
  mysqlRootPassword: ""
  mysqlExistingSecret: "mysql"
  mysqlSecretKeyPassword: "mysql-password"
  mysqlSecretKeyRootPassword: "mysql-root-password"
  appDotnetEnv: "test"
  appCoreBaseDomain: "localhost"
  appCoreMachinekey: "your_core_machinekey"
  DocumentServerUrlPublic: "/ds-vpath/"
  DocumentServerUrlInternal: "http://onlyoffice-document-server/"
  DocumentServerUrlConverter: "/ds-vpath/ConvertService.ashx"
  AppUrlPortal: "http://onlyoffice-proxy:8092"
  redisHost: "redis-master"
  rabbitHost: "rabbitmq"
  kafkaHost: "onlyoffice-kafka"
  elkHost: "elasticsearch-master"
  proxyHost: "onlyoffice-proxy"
  countWorkerConnections: "1024"
  nginxSnvsubstTemplateSuffix: ".template"
  serviceKeepalive: "64"
  apiHost: "onlyoffice-api"
  apiSystemHost: "onlyoffice-api-system"
  calendarHost: "onlyoffice-calendar"
  crmHost: "onlyoffice-crm"
  storageEncryptionHost: "onlyoffice-storage-encryption"
  mailHost: "onlyoffice-mail"
  storageMigrationHost: "onlyoffice-storage-migration"
  notifyHost: "onlyoffice-notify"
  projektsServerHost: "onlyoffice-projects-server"
  urlshortenerHost: "onlyoffice-urlshortener"
  studioNotifyHost: "onlyoffice-studio-notify"
  socketHost: "onlyoffice-socket"
  telegramServiceHost: "onlyoffice-telegram-service"
  peopleServerHost: "onlyoffice-people-server"
  filesHost: "onlyoffice-files"
  filesServicesHost: "onlyoffice-files-services"
  studioHost: "onlyoffice-studio"
  backupHost: "onlyoffice-backup"
  thumbnailsHost: "onlyoffice-thumbnails"
  ssoauthHost: "onlyoffice-ssoauth"
  documentServerHost: "onlyoffice-document-server"
  clearEventsHost: "onlyoffice-clear-events"
  migrationHost: "onlyoffice-migration"
  webhooksServiceHost: "onlyoffice-webhooks-service"
  doceditorHost: "onlyoffice-doceditor"
  backupBackgruondTasksHost: "onlyoffice-backup-background-tasks"
  servicePort: "5050"

images:
  tag: develop
  initContainer:
    initStorage: onlyoffice/4testing-appserver-bin-share
    waitStorage: onlyoffice/4testing-appserver-wait-bin-share
  calendar: onlyoffice/4testing-appserver-calendar
  crm: onlyoffice/4testing-appserver-crm
  files: onlyoffice/4testing-appserver-files
  mail: onlyoffice/4testing-appserver-mail
  people: onlyoffice/4testing-appserver-people-server
  projects: onlyoffice/4testing-appserver-projects-server
  proxy: onlyoffice/4testing-appserver-proxy
  apiSystem: onlyoffice/4testing-appserver-api-system
  api: onlyoffice/4testing-appserver-api
  backup: onlyoffice/4testing-appserver-backup
  filesServices: onlyoffice/4testing-appserver-files-services
  notify: onlyoffice/4testing-appserver-notify
  socket: onlyoffice/4testing-appserver-socket
  ssoauth: onlyoffice/4testing-appserver-ssoauth
  storageEncryption: onlyoffice/4testing-appserver-storage-encryption
  storageMigration: onlyoffice/4testing-appserver-storage-migration
  studioNotify: onlyoffice/4testing-appserver-studio-notify
  studio: onlyoffice/4testing-appserver-studio
  telegramService: onlyoffice/4testing-appserver-telegram-service
  thumbnails: onlyoffice/4testing-appserver-thumbnails
  urlshortener: onlyoffice/4testing-appserver-urlshortener
  clearEvents: onlyoffice/4testing-appserver-clear-events
  backupBackgroundTasks: onlyoffice/4testing-appserver-backup-background
  webhooksService: onlyoffice/4testing-appserver-webhooks-service
  doceditor: onlyoffice/4testing-appserver-doceditor
  migration: onlyoffice/4testing-appserver-migration

persistence:
  storageClass: "nfs"
  appData:
    size: 1Gi
  calendarData:
    size: 1Gi
  crmData:
    size: 1Gi
  filesData:
    size: 1Gi
  mailData:
    size: 1Gi
  peopleData:
    size: 1Gi
  projectData:
    size: 1Gi
  proxyLog:
    size: 1Gi

containerPorts:
  appserver:
    http: 5050
  proxy:
    url: 8081
    internal: 8099
    external: 8092
  socket: 9899
  sso: 9834
  thumbnails: 9800
  urlshortener: 9999
  doceditor: 5013
  backupBackgruondTasks: 5032

podAnnotations:
  rollme: "{{ randAlphaNum 5 | quote }}"

jwt:
  enabled: true
  secret: "jwt_secret"
  header: "AuthorizationJwt"
  inBody: true

livenessProbe:
  enabled: false
  failureThreshold: 2
  httpGet:
    path: /
    port: 5050
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5
  initialDelaySeconds: 45

startupProbe:
  enabled: false
  httpGet:
    path: /
    port: 5050
  failureThreshold: 30
  periodSeconds: 10

readinessProbe:
  enabled: false
  failureThreshold: 2
  httpGet:
    path: /
    port: 5050
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 3

podSecurityContext:
  enabled: false
  runAsUser: 104
  runAsGroup: 107

containerSecurityContext:
  enabled: false
  allowPrivilegeEscalation: false

imagePullSecrets: ""

extraConf:
  secretName: ""
  fileName: appsettings.json

## Appserver common deployment parameters
## This block defines common parameters for all deployments only

podAntiAffinity:
  type: "soft"
  topologyKey: kubernetes.io/hostname
  weight: "100"

nodeSelector: {}

tolerations: []

deploymetsUpdateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

## Appserver People Server deployment parameters

onlyofficePeopleServer:
  replicaCount: 2

## Appserver Files deployment parameters

onlyofficeFiles:
  replicaCount: 2

## Appserver Proxy deployment parameters

onlyofficeProxy:
  replicaCount: 2
  extraConf:
    configMap: ""
    fileName: "10.upstream.conf.upstream"

## Appserver Calendar deployment parameters

onlyofficeCalendar:
  enabled: false
  replicaCount: 2

## Appserver Crm deployment parameters

onlyofficeCrm:
  enabled: false
  replicaCount: 2

## Appserver Mail deployment parameters

onlyofficeMail:
  enabled: false
  replicaCount: 2

## Appserver Project Server deployment parameters

onlyofficeProjectServer:
  enabled: false
  replicaCount: 2

## Appserver common statefulset parameters
## This block defines common parameters for all statefulsets only

statefulsetUpdateStrategy:
  type: RollingUpdate

## Appserver ingress parameters
## This block defines parameters for the Nginx ingress only

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  tls:
    enabled: false
    secretName: tls
  host: ""

## Document server parameters
## This block defines parameters for the document server StatefulSet only

docs:
  image:
    repository: onlyoffice/documentserver
    tag: 7.1.1
    pullPolicy: IfNotPresent

  podSecurityContext:
    enabled: false
    runAsUser: 104
    runAsGroup: 107

  containerPorts:
    http: 80
    https: 443
    spch: 8080
    docs: 8000
    proxy: 8888

  startupProbe:
    enabled: false
    httpGet:
      path: /index.html
      port: 8888
    failureThreshold: 30
    periodSeconds: 10

  readinessProbe:
    enabled: false
    failureThreshold: 2
    httpGet:
      path: /index.html
      port: 8888
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3

  livenessProbe:
    enabled: false
    failureThreshold: 5
    httpGet:
      path: /index.html
      port: 8888
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 45
