kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: scc-app-components
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
  uidRangeMax: 104 
  uidRangeMin: 104
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges: 
  - max: 107
    min: 107
supplementalGroups:
  type: MustRunAs
users: []
groups: []
