kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-docspace-components
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAs
  uid: 104 
seLinuxContext:
  type: MustRunAs
fsGroup:
  type: MustRunAs
  ranges: 
  - max: 107
    min: 107
supplementalGroups:
  type: MustRunAs
users: []
groups: []
