{{- if .Values.backupWorker.enabled }}
apiVersion: apps/v1
kind: {{ .Values.backupWorker.kind }}
metadata:
  name: backup-worker
  namespace: {{ include "apps.namespace" . | quote }}
  labels:
    app: backup-worker
    {{- if .Values.commonLabels }}
    {{- include "apps.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.backupWorker.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.backupWorker.annotations }}
  annotations: {{- include "apps.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.backupWorker.autoscaling.enabled }}
  replicas: {{ default .Values.replicas .Values.backupWorker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: backup-worker
      {{- if .Values.commonLabels }}
      {{- include "apps.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.backupWorker.kind "StatefulSet" }}
  serviceName: backup-worker
  {{- end }}
  {{- if .Values.backupWorker.updateStrategy }}
  {{- if eq .Values.backupWorker.kind "Deployment" }}
  strategy: {{- include "apps.update.strategyType" .Values.backupWorker.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "apps.update.strategyType" .Values.backupWorker.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.backupWorker.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.backupWorker.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: backup-worker
        {{- if .Values.commonLabels }}
        {{- include "apps.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.backupWorker.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.backupWorker.podAnnotations }}
      annotations: {{- include "apps.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "apps.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.backupWorker.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.backupWorker.podSecurityContext.enabled }}
      {{- $psc = .Values.backupWorker.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "apps.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - backup-worker
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - backup-worker
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.backupWorker.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.backupWorker.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.backupWorker.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.backupWorker.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.backupWorker.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.backupWorker.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.backupWorker.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.connections.hostAliases }}
      hostAliases: {{- toYaml .Values.connections.hostAliases | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers.custom }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: backup-worker
        image: {{ include "apps.imageRegistry" (list . .Values.backupWorker.image.registry) }}{{ include "apps.imageRepository" (list . .Values.backupWorker.image.repository) }}:{{ default .Values.images.tag .Values.backupWorker.image.tag }}
        imagePullPolicy: {{ .Values.backupWorker.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.backupWorker.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.backupWorker.containerSecurityContext.enabled }}
        {{- $csc = .Values.backupWorker.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "apps.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.backupWorker.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.backupWorker.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.backupWorker.containerPorts.app }}
          name: app
        {{- if .Values.backupWorker.startupProbe.enabled }}
        startupProbe: {{- omit .Values.backupWorker.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.backupWorker.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.backupWorker.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.backupWorker.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.backupWorker.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.backupWorker.resources | nindent 10 }}
        env:
        - name: MYSQL_USER
          value: {{ default .Values.connections.mysqlUser .Values.backupWorker.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.redis.secretName" . }}
              key: {{ .Values.connections.redisSecretKeyName }}
        - name: RABBIT_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-broker-uri
              key: broker_uri
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.broker.secretName" . }}
              key: {{ .Values.connections.brokerSecretKeyName }}
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.jwt.secretName" . }}
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.jwt.secretName" . }}
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: {{ template "apps.jwt.secretName" . }}
              key: JWT_HEADER
        {{- with .Values.backupWorker.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: docspace
        - secretRef:
            name: {{ template "apps.coreMachineKey.secretName" . }}
        - secretRef:
            name: {{ template "apps.jwt.secretName" . }}
        volumeMounts:
        {{- if .Values.extraConf.secretName }}
        {{- $context := . }}
        {{- range .Values.extraConf.fileName }}
        - name: custom-file
          mountPath: /app/{{ $context.Values.product.name }}/config/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- with .Values.backupWorker.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: docspace-data
          mountPath: /app/{{ .Values.product.name }}/data
      volumes:
      {{- if .Values.extraConf.secretName }}
      - name: custom-file
        secret:
          secretName: {{ .Values.extraConf.secretName }}
      {{- end }}
      {{- with .Values.backupWorker.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - name: docspace-data
        persistentVolumeClaim:
          claimName: {{ template "apps.pvc.data.name" . }}
{{- end }}
