{{- if .Values.healthchecks.enabled }}
apiVersion: apps/v1
kind: {{ .Values.healthchecks.kind }}
metadata:
  name: healthchecks
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: healthchecks
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.healthchecks.replicaCount }}
  selector:
    matchLabels:
      app: healthchecks
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.healthchecks.kind "StatefulSet" }}
  serviceName: healthchecks
  {{- end }}
  {{- if .Values.healthchecks.updateStrategy }}
  {{- if eq .Values.healthchecks.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.healthchecks.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.healthchecks.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.healthchecks.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.healthchecks.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: healthchecks
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - people-server
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
        {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - people-server
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
        {{- end }}
        {{- with .Values.healthchecks.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.healthchecks.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: app-wait-storage
        image: {{ .Values.initContainers.waitStorage.image.repository }}:{{ default .Values.images.tag .Values.initContainers.waitStorage.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.waitStorage.image.pullPolicy }}
        resources: {{- toYaml .Values.initContainers.waitStorage.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      {{- with .Values.initContainers.custom }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: healthchecks
        image: {{ .Values.healthchecks.image.repository }}:{{ default .Values.images.tag .Values.healthchecks.image.tag }}
        imagePullPolicy: {{ .Values.healthchecks.image.pullPolicy }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.healthchecks.containerPorts.healthcheck }}
          name: healthcheck
        {{- if .Values.healthchecks.startupProbe.enabled }}
        startupProbe: {{- omit .Values.healthchecks.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.healthchecks.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.healthchecks.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.healthchecks.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.healthchecks.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.healthchecks.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: healthchecks
        volumeMounts:
        - name: docspace-data
          mountPath: /app/onlyoffice/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
      volumes:
      - name: docspace-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.data.name" . }}
      - name: files-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.files.name" . }}
      - name: people-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.people.name" . }}
{{- end }}
