{{- if .Values.identityApi.enabled }}
apiVersion: apps/v1
kind: {{ .Values.identityApi.kind }}
metadata:
  name: identityApi
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identityApi
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.identityApi.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.identityApi.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.identityApi.replicaCount }}
  selector:
    matchLabels:
      app: identityApi
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.identityApi.kind "StatefulSet" }}
  serviceName: identityApi
  {{- end }}
  {{- if .Values.identityApi.updateStrategy }}
  {{- if eq .Values.identityApi.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.identityApi.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.identityApi.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.identityApi.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.identityApi.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: identityApi
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.identityApi.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.identityApi.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.identityApi.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.identityApi.podSecurityContext.enabled }}
      {{- $psc = .Values.identityApi.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - identityApi
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - identityApi
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.identityApi.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.identityApi.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.identityApi.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.identityApi.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.identityApi.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.identityApi.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.identityApi.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: identityApi
        image: {{ include "docspace.imageRepository" (list . .Values.identityApi.image.repository) }}:{{ default .Values.images.tag .Values.identityApi.image.tag }}
        imagePullPolicy: {{ .Values.identityApi.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.identityApi.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.identityApi.containerSecurityContext.enabled }}
        {{- $csc = .Values.identityApi.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.identityApi.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.identityApi.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.identityApi.containerPorts.identityApi }}
          name: identityApi
        {{- if .Values.identityApi.startupProbe.enabled }}
        startupProbe: {{- omit .Values.identityApi.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identityApi.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.identityApi.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identityApi.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.identityApi.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.identityApi.resources | nindent 10 }}
        env:
        - name: SPRING_APPLICATION_NAME
          value: ASC.Identity.Registration
        - name: SERVER_PORT
          value: {{ .Values.identityApi.containerPorts.identityApi }}
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: JDBC_URL
          value: mysql
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: JDBC_USER_NAME
          value: root
        - name: JDBC_DATABASE
          value: {{ .Values.connections.mysqlDatabase }}
        - name: RABBIT_HOST
          value: {{ .Values.connections.brokerHost }}
        - name: REDIS_HOST
          value: {{ .Values.connections.redisHost }}  
        envFrom:
        - configMapRef:
            name: docspace
{{- end }}
