{{- if .Values.identity.enabled }}
apiVersion: apps/v1
kind: {{ .Values.identity.identityApi.kind }}
metadata:
  name: identity-api
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity-api
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.identity.identityApi.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.identity.identityApi.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.identity.identityApi.replicaCount }}
  selector:
    matchLabels:
      app: identity-api
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.identity.identityApi.kind "StatefulSet" }}
  serviceName: identity-api
  {{- end }}
  {{- if .Values.identity.identityApi.updateStrategy }}
  {{- if eq .Values.identity.identityApi.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.identity.identityApi.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.identity.identityApi.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.identity.identityApi.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.identity.identityApi.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: identity-api
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.identity.identityApi.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.identity.identityApi.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.identity.identityApi.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.identity.identityApi.podSecurityContext.enabled }}
      {{- $psc = .Values.identity.identityApi.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - identity-api
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - identity-api
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.identity.identityApi.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.identity.identityApi.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.identity.identityApi.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.identity.identityApi.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.identity.identityApi.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.identity.identityApi.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.identity.identityApi.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: identity-api
        image: {{ include "docspace.imageRepository" (list . .Values.identity.identityApi.image.repository) }}:{{ default .Values.images.tag .Values.identity.identityApi.image.tag }}
        imagePullPolicy: {{ .Values.identity.identityApi.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.identity.identityApi.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.identity.identityApi.containerSecurityContext.enabled }}
        {{- $csc = .Values.identity.identityApi.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.identityApi.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.identity.identityApi.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.identity.identityApi.containerPorts.api }}
          name: api
        {{- if .Values.identity.identityApi.startupProbe.enabled }}
        startupProbe: {{- omit .Values.identity.identityApi.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.identityApi.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.identity.identityApi.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.identityApi.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.identity.identityApi.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.identity.identityApi.resources | nindent 10 }}
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: identity
              key: SERVER_PORT_IDENTITY_API
        - name: SERVER_PORT
          value: {{ .Values.identity.identityApi.containerPorts.api | quote }}
        - name: JDBC_USER_NAME
          value: {{ default .Values.connections.mysqlUser .Values.identity.identityApi.mysqlUser }}
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.redis.secretName" . }}
              key: {{ .Values.connections.redisSecretKeyName }}
        - name: RABBIT_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-broker-uri
              key: broker_uri
        envFrom:
        - configMapRef:
            name: identity
{{- end }}
