{{- if .Values.identity.enabled }}
apiVersion: apps/v1
kind: {{ .Values.identity.kind }}
metadata:
  name: identity
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.identity.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.identity.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.identity.replicaCount }}
  selector:
    matchLabels:
      app: identity
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.identity.kind "StatefulSet" }}
  serviceName: identity
  {{- end }}
  {{- if .Values.identity.updateStrategy }}
  {{- if eq .Values.identity.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.identity.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.identity.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.identity.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.identity.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: identity
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.identity.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.identity.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.identity.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.identity.podSecurityContext.enabled }}
      {{- $psc = .Values.identity.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - identity
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - identity
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.identity.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.identity.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.identity.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.identity.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.identity.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.identity.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.identity.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: identity
        image: {{ include "docspace.imageRepository" (list . .Values.identity.image.repository) }}:{{ default .Values.images.tag .Values.identity.image.tag }}
        imagePullPolicy: {{ .Values.identity.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.identity.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.identity.containerSecurityContext.enabled }}
        {{- $csc = .Values.identity.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.identity.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.identity.containerPorts.identity }}
          name: identity
        {{- if .Values.identity.startupProbe.enabled }}
        startupProbe: {{- omit .Values.identity.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.identity.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.identity.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.identity.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.identity.resources | nindent 10 }}
        env:
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: identity
              key: SERVER_PORT_IDENTITY
        - name: SERVER_PORT
          value: {{ .Values.identity.containerPorts.identity | quote }}
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        envFrom:
        - configMapRef:
            name: identity
{{- end }}
