apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: lemmav/identity-authorization:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_APPLICATION_NAME
          value: "ASC.Identity.Authorization"
        - name: SERVER_PORT
          value: "8080"
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: JDBC_URL
          value: {{ .Values.connections.mysqlHost }}
        - name: JDBC_USER_NAME
          value: {{ .Values.connections.mysqlUser }}
        - name: JDBC_DATABASE
          value: {{ .Values.connections.mysqlDatabase }}
        - name: RABBIT_HOST
          value: "onlyoffice-rabbitmq"
        - name: REDIS_HOST
          value: "onlyoffice-redis"
        envFrom:
        - configMapRef:
            name: docspace
