{{- if .Values.opensearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: opensearch
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  serviceName: opensearch
  {{- if .Values.opensearch.updateStrategy }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.opensearch.updateStrategy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: opensearch
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if .Values.opensearch.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.opensearch.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.opensearch.podAffinity .Values.opensearch.nodeAffinity }}
      affinity:
        {{- with .Values.opensearch.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.opensearch.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: change-volume-owner
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        command: ['chown', '-R', '1000:1000', '/usr/share/opensearch/data']
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      {{- with .Values.opensearch.initContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: opensearch
        image: {{ .Values.opensearch.image.repository }}:{{ .Values.opensearch.image.tag }}
        imagePullPolicy: {{ .Values.opensearch.image.pullPolicy }}
        {{- if .Values.opensearch.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.opensearch.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        {{- if .Values.opensearch.startupProbe.enabled }}
        startupProbe: {{- omit .Values.opensearch.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.opensearch.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.opensearch.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.opensearch.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.opensearch.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.opensearch.resources | nindent 10 }}
        env:
        - name: discovery.type
          value: "single-node"
        - name: DISABLE_SECURITY_PLUGIN
          value: "true"
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g -Dlog4j2.formatMsgNoLookups=true"
        - name: indices.fielddata.cache.size
          value: "30%"
        - name: indices.memory.index_buffer_size
          value: "30%"
        volumeMounts:
        - name: opensearch-data
          mountPath: /usr/share/opensearch/data
      volumes:
      - name: opensearch-data
        persistentVolumeClaim:
          claimName: opensearch-data
{{- end }}
