{{- if .Values.proxyFrontend.enabled }}
apiVersion: apps/v1
kind: {{ .Values.proxyFrontend.kind }}
metadata:
  name: proxy-frontend
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: proxy-frontend
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.proxyFrontend.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.proxyFrontend.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.proxyFrontend.autoscaling.enabled }}
  replicas: {{ .Values.proxyFrontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: proxy-frontend
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.proxyFrontend.kind "StatefulSet" }}
  serviceName: {{ template "docspace.svc.proxyFrontend.name" . }}
  {{- end }}
  {{- if .Values.proxyFrontend.updateStrategy }}
  {{- if eq .Values.proxyFrontend.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.proxyFrontend.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.proxyFrontend.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.proxyFrontend.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.proxyFrontend.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: proxy-frontend
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.proxyFrontend.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.proxyFrontend.podAnnotations "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.proxyFrontend.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.proxyFrontend.podSecurityContext.enabled }}
      {{- $psc = .Values.proxyFrontend.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - proxy-frontend
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - proxy-frontend
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.proxyFrontend.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.proxyFrontend.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.proxyFrontend.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.proxyFrontend.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.proxyFrontend.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.proxyFrontend.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.proxyFrontend.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.connections.hostAliases }}
      hostAliases: {{- toYaml .Values.connections.hostAliases | nindent 8 }}
      {{- end }}
      {{- with .Values.proxyFrontend.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: proxy-frontend
        image: {{ .Values.proxyFrontend.image.repository }}:{{ .Values.proxyFrontend.image.tag }}
        imagePullPolicy: {{ .Values.proxyFrontend.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.proxyFrontend.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.proxyFrontend.containerSecurityContext.enabled }}
        {{- $csc = .Values.proxyFrontend.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.proxyFrontend.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.proxyFrontend.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.proxyFrontend.containerPorts.http }}
          name: http
        - containerPort: {{ .Values.proxyFrontend.containerPorts.https }}
          name: https
        {{- if .Values.proxyFrontend.startupProbe.enabled }}
        startupProbe: {{- omit .Values.proxyFrontend.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.proxyFrontend.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.proxyFrontend.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.proxyFrontend.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.proxyFrontend.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.proxyFrontend.resources | nindent 10 }}
        {{ if .Values.proxyFrontend.extraEnvVars }}
        env:
        {{- with .Values.proxyFrontend.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        volumeMounts:
        {{- if .Values.proxyFrontend.extraConf.confd.configMap }}
        {{- range .Values.proxyFrontend.extraConf.confd.fileName }}
        - name: confd-file
          mountPath: /etc/nginx/conf.d/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.proxyFrontend.extraConf.customConfd.configMap }}
        {{- range .Values.proxyFrontend.extraConf.customConfd.fileName }}
        - name: custom-confd-file
          mountPath: /etc/nginx/conf.d/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.proxyFrontend.tls.secretName }}
        - name: tls
          mountPath: {{ .Values.proxyFrontend.tls.mountPath }}
          readOnly: true
        {{- end }}
        {{- with .Values.proxyFrontend.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
      {{- if .Values.proxyFrontend.extraConf.confd.configMap }}
      - name: confd-file
        configMap:
          name: {{ .Values.proxyFrontend.extraConf.confd.configMap }}
      {{- end }}
      {{- if .Values.proxyFrontend.extraConf.customConfd.configMap }}
      - name: custom-confd-file
        configMap:
          name: {{ .Values.proxyFrontend.extraConf.customConfd.configMap }}
      {{- end }}
      {{- with .Values.proxyFrontend.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.proxyFrontend.tls.secretName }}
      - name: tls
        secret:
          secretName: {{ .Values.proxyFrontend.tls.secretName }}
          items:
          - key: {{ .Values.proxyFrontend.tls.crtName }}
            path: {{ .Values.proxyFrontend.tls.crtName }}
          - key: {{ .Values.proxyFrontend.tls.keyName }}
            path: {{ .Values.proxyFrontend.tls.keyName }}
      {{- end }}
{{- end }}
