{{- if .Values.studio.enabled }}
apiVersion: apps/v1
kind: {{ .Values.studio.kind }}
metadata:
  name: studio
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: studio
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.studio.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.studio.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: studio
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  {{- if eq .Values.studio.kind "StatefulSet" }}
  serviceName: studio
  {{- end }}
  {{- if .Values.studio.updateStrategy }}
  {{- if eq .Values.studio.kind "Deployment" }}
  strategy: {{- include "docspace.update.strategyType" .Values.studio.updateStrategy }}
  {{- else }}
  updateStrategy: {{- include "docspace.update.strategyType" .Values.studio.updateStrategy }}
  {{- end }}
  {{- end }}
  {{- if eq .Values.studio.kind "StatefulSet" }}
  podManagementPolicy: {{ .Values.studio.podManagementPolicy }}
  {{- end }}
  template:
    metadata:
      labels:
        app: studio
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.studio.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.studio.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.studio.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.studio.podSecurityContext.enabled }}
      {{- $psc = .Values.studio.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.type "preferred" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - studio
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
          {{- else if eq .Values.podAntiAffinity.type "required" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - studio
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
          {{- end }}
          {{- with .Values.studio.customPodAntiAffinity }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.studio.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.studio.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- if or .Values.nodeSelector .Values.studio.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.studio.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.studio.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.studio.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: app-wait-storage
        image: {{ include "docspace.imageRepository" (list . .Values.initContainers.waitStorage.image.repository) }}:{{ default .Values.images.tag .Values.initContainers.waitStorage.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.waitStorage.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.studio.containerSecurityContext.enabled }}
        {{- $icsc := dict }}
        {{- if .Values.studio.containerSecurityContext.enabled }}
        {{- $icsc = .Values.studio.containerSecurityContext }}
        {{- else }}
        {{- $icsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $icsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.initContainers.waitStorage.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      {{- with .Values.initContainers.custom }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: studio
        image: {{ include "docspace.imageRepository" (list . .Values.studio.image.repository) }}:{{ default .Values.images.tag .Values.studio.image.tag }}
        imagePullPolicy: {{ .Values.studio.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.studio.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.studio.containerSecurityContext.enabled }}
        {{- $csc = .Values.studio.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        {{- if .Values.studio.lifecycleHooks }}
        lifecycle: {{- toYaml .Values.studio.lifecycleHooks | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.studio.containerPorts.app }}
          name: app
        {{- if .Values.studio.startupProbe.enabled }}
        startupProbe: {{- omit .Values.studio.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.studio.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.studio.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.studio.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.studio.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.studio.resources | nindent 10 }}
        env:
        - name: MYSQL_USER
          value: {{ default .Values.connections.mysqlUser .Values.studio.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.redis.secretName" . }}
              key: {{ .Values.connections.redisSecretKeyName }}
        - name: RABBIT_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-broker-uri
              key: broker_uri
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_HEADER
        {{- with .Values.studio.extraEnvVars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: docspace
        - secretRef:
            name: {{ template "docspace.coreMachineKey.secretName" . }}
        - secretRef:
            name: {{ template "docspace.jwt.secretName" . }}
        volumeMounts:
        {{- if .Values.extraConf.secretName }}
        {{- $context := . }}
        {{- range .Values.extraConf.fileName }}
        - name: custom-file
          mountPath: /app/{{ $context.Values.product.name }}/config/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- with .Values.studio.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: docspace-data
          mountPath: /app/{{ .Values.product.name }}/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
      volumes:
      {{- if .Values.extraConf.secretName }}
      - name: custom-file
        secret:
          secretName: {{ .Values.extraConf.secretName }}
      {{- end }}
      {{- with .Values.studio.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      - name: docspace-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.data.name" . }}
      - name: files-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.files.name" . }}
      - name: people-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.people.name" . }}
{{- end }}
