apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-clear-indexes
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: elasticsearch-clear-indexes
          image: onlyoffice/docs-utils:9.0.3-1
          command: ["/bin/sh", "-c"]
          args: ["/elasticsearch-clear-indexes.sh"]
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_PORT
            - name: MYSQL_USER
              value: onlyoffice_user
            - name: MYSQL_PASSWORD
              value: onlyoffice_user_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_DATABASE
            - name: ELK_SHEME
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_SHEME
            - name: ELK_HOST
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_HOST
            - name: ELK_PORT
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_PORT
          volumeMounts:
            - name: elasticsearch-clear-indexes
              mountPath: /elasticsearch-clear-indexes.sh
              subPath: elasticsearch-clear-indexes.sh
      restartPolicy: Never
      volumes:
        - name: elasticsearch-clear-indexes
          configMap:
            name: elasticsearch-clear-indexes
            defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-clear-indexes
data:
  elasticsearch-clear-indexes.sh: |
    #!/bin/bash
    echo -e "\e[0;32m The indexes will be cleared \e[0m"
    mysql \
    -h "$MYSQL_HOST" \
    -P "$MYSQL_PORT" \
    -u "$MYSQL_USER" \
    -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" \
    -e "TRUNCATE webstudio_index;"
    if [[ "$ELK_SHEME" == "https" ]]; then
      curl -XDELETE $ELK_SHEME://$ELK_HOST/files_folder
      curl -XDELETE $ELK_SHEME://$ELK_HOST/files_file
    else
      curl -XDELETE $ELK_SHEME://$ELK_HOST:$ELK_PORT/files_folder
      curl -XDELETE $ELK_SHEME://$ELK_HOST:$ELK_PORT/files_file
    fi
    echo -e "\e[0;32m Index cleanup is complete \e[0m"
