apiVersion: batch/v1
kind: Job
metadata:
  name: remove-indexes
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - name: remove-indexes
          image: mysql:8.0.36-debian
          command: ["/bin/sh", "-c"]
          args: ["/remove-indexes.sh"]
          env:
            - name: MYSQL_USER
              value: onlyoffice_user
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: MYSQL_DATABASE
            - name: MYSQL_PASSWORD
              value: onlyoffice_user_password
            - name: ELK_HOST
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_HOST
            - name: ELK_PORT
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_PORT
          volumeMounts:
            - name: remove-indexes
              mountPath: /remove-indexes.sh
              subPath: remove-indexes.sh
      restartPolicy: Never
      volumes:
        - name: remove-indexes
          configMap:
            name: remove-indexes
            defaultMode: 0777
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: remove-indexes
data:
  remove-indexes.sh: |
    #!/bin/bash
    apt update && apt-get install -y curl jq
    mysql \
    -h "$MYSQL_HOST" \
    -P "$MYSQL_PORT" \
    -u "$MYSQL_USER" \
    -p"$MYSQL_PASSWORD" "$MYSQL_DATABASE" \
    -e "TRUNCATE webstudio_index;"
    curl -XDELETE http://$ELK_HOST:$ELK_PORT/files_folder
    curl -XDELETE http://$ELK_HOST:$ELK_PORT/files_file
    
