{{- if .Values.onlyofficeCrm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-crm
  labels:
    app: onlyoffice-crm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlyoffice-crm
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlyoffice-crm
    spec:
      {{ if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      {{ end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onlyoffice-crm
              topologyKey: {{ .Values.antiAffinity.topologyKey }}
            weight: {{ .Values.antiAffinity.weight }}
        {{- else if eq .Values.antiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onlyoffice-crm
            topologyKey: {{ .Values.antiAffinity.topologyKey }}
        {{- end }}
      imagePullSecrets:
      - name: myregistrykey
      initContainers:
      - name: appserver-wait-storage
        image: {{ .Values.images.initContainer.waitStorage }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      containers:
      - name: onlyoffice-crm
        image: {{ .Values.images.crm }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-password
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: appserver-all
        - secretRef:
            name: jwt
        ports:
        - containerPort: {{ .Values.ports.appserver.http }}
          name: http
    #    livenessProbe:
    #      failureThreshold: 2
    #      httpGet:
    #        path: /
    #        port: 5050
    #      periodSeconds: 10
    #      successThreshold: 1
    #      timeoutSeconds: 5
    #      initialDelaySeconds: 45
    #    securityContext:
    #      allowPrivilegeEscalation: false
        volumeMounts:
        - name: app-data
          mountPath: /app/onlyoffice/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
        {{ if .Values.onlyofficeProjectServer.enabled }}
        - name: project-data
          mountPath: /var/www/products/ASC.Projects/server/
        {{ end }}
        {{ if .Values.onlyofficeCalendar.enabled }}
        - name: calendar-data
          mountPath: /var/www/products/ASC.Calendar/server/
        {{ end }}
        {{ if .Values.onlyofficeMail.enabled }}
        - name: mail-data
          mountPath: /var/www/products/ASC.Mail/server/
        {{ end }}
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data
      - name: files-data
        persistentVolumeClaim:
          claimName: files-data
      - name: people-data
        persistentVolumeClaim:
          claimName: people-data
      {{ if .Values.onlyofficeCrm.enabled }}
      - name: crm-data
        persistentVolumeClaim:
          claimName: crm-data
      {{ end }}
      {{ if .Values.onlyofficeProjectServer.enabled }}
      - name: project-data
        persistentVolumeClaim:
          claimName: project-data
      {{ end }}
      {{ if .Values.onlyofficeCalendar.enabled }}
      - name: calendar-data
        persistentVolumeClaim:
          claimName: calendar-data
      {{ end }}
      {{ if .Values.onlyofficeMail.enabled }}
      - name: mail-data
        persistentVolumeClaim:
          claimName: mail-data
      {{ end }}
{{- end }}
