apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-proxy
  labels:
    app: onlyoffice-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlyoffice-proxy
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: onlyoffice-proxy
    spec:
      {{ if .Values.securityContext.enabled }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      {{ end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.antiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onlyoffice-proxy
              topologyKey: {{ .Values.antiAffinity.topologyKey }}
            weight: {{ .Values.antiAffinity.weight }}
        {{- else if eq .Values.antiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onlyoffice-proxy
            topologyKey: {{ .Values.antiAffinity.topologyKey }}
        {{- end }}
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: onlyoffice-proxy
        image: {{ .Values.images.proxy }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-password
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: appserver-all
        - configMapRef:
            name: appserver-proxy
        - secretRef:
            name: jwt
        ports:
        - containerPort: {{ .Values.ports.appserver.http }}
          name: http
        - containerPort: 8081
          name: url
        - containerPort: 8099
          name: internal
        - containerPort: 8092
          name: external
    #    livenessProbe:
    #      failureThreshold: 2
    #      httpGet:
    #        path: /
    #        port: 8081
    #      periodSeconds: 10
    #      successThreshold: 1
    #      timeoutSeconds: 5
    #      initialDelaySeconds: 45
    #    securityContext:
    #      allowPrivilegeEscalation: false
        volumeMounts:
        - name: proxy-log
          mountPath: /var/log/nginx
        - name: change-hosts
          mountPath: /docker-entrypoint.d/change-hosts.sh
          subPath: change-hosts.sh
        - name: proxy-upstream
          mountPath: /etc/nginx/templates/upstream.conf.template
          subPath: upstream.conf.template
      volumes:
      - name: proxy-log
        persistentVolumeClaim:
          claimName: proxy-log
      - name: change-hosts
        configMap:
          name: change-hosts
          defaultMode: 0755
      - name: proxy-upstream
        configMap:
          name: proxy-upstream
