apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-proxy
  labels:
    app: onlyoffice-proxy
spec:
  replicas: {{ .Values.onlyofficeProxy.replicaCount }}
  selector:
    matchLabels:
      app: onlyoffice-proxy
  {{- if .Values.deploymetsUpdateStrategy }}
  strategy: {{ template "app.update.strategyType" . }}
  {{- end }}
  template:
    metadata:
      labels:
        app: onlyoffice-proxy
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onlyoffice-proxy
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
        {{- else if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onlyoffice-proxy
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }} 
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: onlyoffice-proxy
        image: {{ .Values.images.proxy }}:{{ .Values.images.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        envFrom:
        - configMapRef:
            name: app-all
        - configMapRef:
            name: app-proxy
        ports:
        - containerPort: {{ .Values.containerPorts.proxy.external }}
          name: external
        {{- if .Values.onlyofficeProxy.startupProbe.enabled }}
        startupProbe: {{- omit .Values.onlyofficeProxy.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.onlyofficeProxy.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.onlyofficeProxy.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.onlyofficeProxy.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.onlyofficeProxy.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.onlyofficeProxy.extraConf.initScripts.configMap }}
        {{- range .Values.onlyofficeProxy.extraConf.initScripts.fileName }}
        - name: init-scripts
          mountPath: /docker-entrypoint.d/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.onlyofficeProxy.extraConf.customInitScripts.configMap }}
        {{- range .Values.onlyofficeProxy.extraConf.customInitScripts.fileName }}
        - name: custom-init-scripts
          mountPath: /docker-entrypoint.d/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.onlyofficeProxy.extraConf.templates.configMap }}
        {{- range .Values.onlyofficeProxy.extraConf.templates.fileName }}
        - name: template-files
          mountPath: /etc/nginx/templates/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.onlyofficeProxy.extraConf.confd.configMap }}
        {{- range .Values.onlyofficeProxy.extraConf.confd.fileName }}
        - name: confd-file
          mountPath: /etc/nginx/conf.d/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        - name: proxy-log
          mountPath: /var/log/nginx
      volumes:
      {{- if .Values.onlyofficeProxy.extraConf.initScripts.configMap }}
      - name: init-scripts
        configMap:
          name: {{ .Values.onlyofficeProxy.extraConf.initScripts.configMap }}
          defaultMode: 0755
      {{- end }}
      {{- if .Values.onlyofficeProxy.extraConf.customInitScripts.configMap }}
      - name: custom-init-scripts
        configMap:
          name: {{ .Values.onlyofficeProxy.extraConf.customInitScripts.configMap }}
          defaultMode: 0755
      {{- end }}
      {{- if .Values.onlyofficeProxy.extraConf.templates.configMap }}
      - name: template-files
        configMap:
          name: {{ .Values.onlyofficeProxy.extraConf.templates.configMap }}
      {{- end }}
      {{- if .Values.onlyofficeProxy.extraConf.confd.configMap }}
      - name: confd-file
        configMap:
          name: {{ .Values.onlyofficeProxy.extraConf.confd.configMap }}
      {{- end }}
      - name: proxy-log
        persistentVolumeClaim:
          claimName: {{ template "app.pvc.proxy.name" . }}
