{{- if .Values.onlyofficeProjectServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-projects-server
  labels:
    app: onlyoffice-projects-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onlyoffice-projects-server
  {{- if .Values.updateStrategy }}
  strategy: {{ template "appserver.update.strategyType" . }}
  {{- end }}
  template:
    metadata:
      labels:
        app: onlyoffice-projects-server
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onlyoffice-projects-server
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
        {{- else if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onlyoffice-projects-server
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }} 
      imagePullSecrets:
      - name: myregistrykey
      initContainers:
      - name: appserver-wait-storage
        image: {{ .Values.images.initContainer.waitStorage }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      containers:
      - name: onlyoffice-projects-server
        image: {{ .Values.images.projects }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: mysql-password
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: appserver-all
        - secretRef:
            name: jwt
        ports:
        - containerPort: {{ .Values.ports.appserver.http }}
          name: http
        {{ if .Values.readinessProbeEnabled }}
        readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{ end }}
        {{ if .Values.livenessProbeEnabled }}
        livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{ end }}
        {{ if .Values.startupProbeEnabled }}
        startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 10 }}
        {{ end }}
    #    securityContext:
    #      allowPrivilegeEscalation: false
        volumeMounts:
        - name: app-data
          mountPath: /app/onlyoffice/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
        {{ if .Values.onlyofficeCrm.enabled }}
        - name: crm-data
          mountPath: /var/www/products/ASC.CRM/server/
        {{ end }}
        {{ if .Values.onlyofficeCalendar.enabled }}
        - name: calendar-data
          mountPath: /var/www/products/ASC.Calendar/server/
        {{ end }}
        {{ if .Values.onlyofficeMail.enabled }}
        - name: mail-data
          mountPath: /var/www/products/ASC.Mail/server/
        {{ end }}
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data
      - name: files-data
        persistentVolumeClaim:
          claimName: files-data
      - name: people-data
        persistentVolumeClaim:
          claimName: people-data
      {{ if .Values.onlyofficeCrm.enabled }}
      - name: crm-data
        persistentVolumeClaim:
          claimName: crm-data
      {{ end }}
      {{ if .Values.onlyofficeProjectServer.enabled }}
      - name: project-data
        persistentVolumeClaim:
          claimName: project-data
      {{ end }}
      {{ if .Values.onlyofficeCalendar.enabled }}
      - name: calendar-data
        persistentVolumeClaim:
          claimName: calendar-data
      {{ end }}
      {{ if .Values.onlyofficeMail.enabled }}
      - name: mail-data
        persistentVolumeClaim:
          claimName: mail-data
      {{ end }}
{{- end }}
