apiVersion: apps/v1
kind: Deployment
metadata:
  name: onlyoffice-proxy
  labels:
    app: onlyoffice-proxy
spec:
  replicas: {{ .Values.onlyofficeProxy.replicaCount }}
  selector:
    matchLabels:
      app: onlyoffice-proxy
  {{- if .Values.deploymetsUpdateStrategy }}
  strategy: {{ template "app.update.strategyType" . }}
  {{- end }}
  template:
    metadata:
      labels:
        app: onlyoffice-proxy
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
        {{- if eq .Values.podAntiAffinity.type "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - onlyoffice-proxy
              topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
            weight: {{ .Values.podAntiAffinity.weight }}
        {{- else if eq .Values.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - onlyoffice-proxy
            topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }} 
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: onlyoffice-proxy
        image: {{ .Values.images.proxy }}:{{ .Values.images.tag }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyRootPassword }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: app-all
        - configMapRef:
            name: app-proxy
        - secretRef:
            name: jwt
        ports:
        - containerPort: {{ .Values.containerPorts.app }}
          name: app
        - containerPort: {{ .Values.containerPorts.proxy.url }}
          name: url
        - containerPort: {{ .Values.containerPorts.proxy.internal }}
          name: internal
        - containerPort: {{ .Values.containerPorts.proxy.external }}
          name: external
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe: {{- omit .Values.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.onlyofficeProxy.extraConf.configMap }}
        - name: custom-file
          mountPath: /etc/nginx/templates/{{ .Values.onlyofficeProxy.extraConf.fileName }}
          subPath: {{ .Values.onlyofficeProxy.extraConf.fileName }}
        {{- end }}
        - name: proxy-log
          mountPath: /var/log/nginx
        - name: change-hosts
          mountPath: /docker-entrypoint.d/change-hosts.sh
          subPath: change-hosts.sh
        - name: proxy-upstream
          mountPath: /etc/nginx/templates/upstream.conf.template
          subPath: upstream.conf.template
      volumes:
      {{- if .Values.onlyofficeProxy.extraConf.configMap }}
      - name: custom-file
        configMap:
          name: {{ .Values.onlyofficeProxy.extraConf.configMap }}
      {{- end }}
      - name: proxy-log
        persistentVolumeClaim:
          claimName: proxy-log
      - name: change-hosts
        configMap:
          name: change-hosts
          defaultMode: 0755
      - name: proxy-upstream
        configMap:
          name: proxy-upstream
