{{- if and .Values.gateway.enabled .Values.gateway.clientSettingsPolicy }}
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: docspace-client
  namespace: {{ include "apps.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "apps.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: docspace
  {{- with .Values.gateway.clientSettingsPolicy }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
