{{- if and .Values.api.enabled (eq .Values.connections.apiHost "api") }}
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: api
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.api.containerPorts.app }}
    name: app
    targetPort: {{ .Values.api.containerPorts.app }}
  selector:
    app: api
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
