apiVersion: v1
kind: Service
metadata:
  name: backup
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: backup
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.backup.containerPorts.app }}
    name: app
    targetPort: {{ .Values.backup.containerPorts.app }}
  selector:
    statefulset.kubernetes.io/pod-name: backup-0
  type: ClusterIP
