apiVersion: v1
kind: Service
metadata:
  name: clear-events
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: clear-events
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.clearEvents.containerPorts.app }}
    name: app
    targetPort: {{ .Values.clearEvents.containerPorts.app }}
  selector:
    app: clear-events
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
