{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ include "app.namespace" . | quote }}
  labels:
    app: elasticsearch
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: 9200
    name: http
    targetPort: 9200
  - port: 9300
    name: transport
    targetPort: 9300
  selector:
    statefulset.kubernetes.io/pod-name: elasticsearch-0
  type: ClusterIP
{{- end }}
