apiVersion: v1
kind: Service
metadata:
  name: files
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.files.containerPorts.app }}
    name: app
    targetPort: {{ .Values.files.containerPorts.app }}
  selector:
    app: files
  type: ClusterIP
