{{- if and .Values.files.enabled (eq .Values.connections.filesHost "files" ) }}
apiVersion: v1
kind: Service
metadata:
  name: files
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: files
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.files.containerPorts.app }}
    name: app
    targetPort: {{ .Values.files.containerPorts.app }}
  selector:
    app: files
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
