apiVersion: v1
kind: Service
metadata:
  name: files-services
  namespace: {{ include "app.namespace" . | quote }}
  labels:
    app: files-services
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.filesServices.containerPorts.app }}
    name: app
    targetPort: {{ .Values.filesServices.containerPorts.app }}
  selector:
    statefulset.kubernetes.io/pod-name: files-services-0
  type: ClusterIP
