apiVersion: v1
kind: Service
metadata:
  name: healthchecks
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.healthchecks.containerPorts.healthcheck }}
    name: healthcheck
    targetPort: {{ .Values.healthchecks.containerPorts.healthcheck }}
  selector:
    app: healthchecks
  type: ClusterIP
