apiVersion: v1
kind: Service
metadata:
  name: identity-api
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity-api
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: 9090
    name: identity-api
    targetPort: 9090
  selector:
    app: identity-api
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP