apiVersion: v1
kind: Service
metadata:
  name: identity-cache
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity-cache
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 5701
    name: identity-cache
    targetPort: 5701
  selector:
    identity: cache
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
