apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: identity
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: 8080
    name: identity
    targetPort: 8080
  selector:
    app: identity
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP