{{- if and .Values.login.enabled (eq .Values.connections.loginHost "login") }}
apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: login
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.login.containerPorts.login }}
    name: login
    targetPort: {{ .Values.login.containerPorts.login }}
  selector:
    app: login
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
