apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: {{ include "app.namespace" . | quote }}
  labels:
    app: login
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.login.containerPorts.login }}
    name: login
    targetPort: {{ .Values.login.containerPorts.login }}
  selector:
    statefulset.kubernetes.io/pod-name: login-0
  type: ClusterIP
