apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-proxy
spec:
  ports:
  - port: 5050
    name: http
    targetPort: 5050
  - port: 8081
    name: url
    targetPort: 8081
  - port: 8099
    name: internal
    targetPort: 8099
  - port: 8092
    name: external
    targetPort: 8092
  selector:
    app: onlyoffice-proxy
  type: ClusterIP
