apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-projects-server
spec:
  ports:
  - port: 5050
    name: http
    targetPort: 5050
  selector:
    app: onlyoffice-projects-server
  type: ClusterIP
