{{- if eq .Values.product.name "appsever" }}
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-storage-encryption
  labels:
    app: onlyoffice-storage-encryption
spec:
  ports:
  - port: {{ .Values.containerPorts.app }}
    name: app
    targetPort: {{ .Values.containerPorts.app }}
  selector:
    statefulset.kubernetes.io/pod-name: onlyoffice-storage-encryption-0
  type: ClusterIP
{{- end }}
