apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-urlshortener
  labels:
    app: onlyoffice-urlshortener
spec:
  ports:
  - port: 5050
    name: http
    targetPort: {{ .Values.ports.appserver.http }}
  - port: 9999
    name: urls
    targetPort: {{ .Values.ports.urlshortener }}
  selector:
    statefulset.kubernetes.io/pod-name: onlyoffice-urlshortener-0
  type: ClusterIP
