apiVersion: v1
kind: Service
metadata:
  name: onlyflow-frontend
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: onlyflow-frontend
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 3000
    name: onlyflow-frontend
    targetPort: 3000
  selector:
    app: onlyflow-frontend
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
