apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-document-server
  labels:
    app: onlyoffice-document-server
spec:
  ports:
  - port: {{ .Values.containerPorts.docs.http }}
    name: http
    targetPort: {{ .Values.containerPorts.docs.http }}
  - port: {{ .Values.containerPorts.docs.https }}
    name: https
    targetPort: {{ .Values.containerPorts.docs.https }}
  - port: {{ .Values.containerPorts.docs.spch }}
    name: spch
    targetPort: {{ .Values.containerPorts.docs.spch }}
  - port: {{ .Values.containerPorts.docs.docs }}
    name: docs
    targetPort: {{ .Values.containerPorts.docs.docs }}
  - port: {{ .Values.containerPorts.docs.prox }}
    name: prox
    targetPort: {{ .Values.containerPorts.docs.prox }}
  selector:
    statefulset.kubernetes.io/pod-name: onlyoffice-document-server-0
  type: ClusterIP
