apiVersion: v1
kind: Service
metadata:
  name: people-server
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.peopleServer.containerPorts.app }}
    name: app
    targetPort: {{ .Values.peopleServer.containerPorts.app }}
  selector:
    app: people-server
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
