{{- if .Values.langflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: pgvector
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 5432
    name: pgvector
    targetPort: 5432
  selector:
    app: pgvector
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
