{{- if and .Values.proxyFrontend.enabled (eq (include "docspace.svc.proxyFrontend.create" .) "true") }}
apiVersion: v1
kind: Service
metadata:
  name: proxy-frontend
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: proxy-frontend
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.proxyFrontend.service.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.proxyFrontend.service.annotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.proxyFrontend.service.port.http }}
    name: http
    targetPort: {{ .Values.proxyFrontend.containerPorts.http }}
  - port: {{ .Values.proxyFrontend.service.port.https }}
    name: https
    targetPort: {{ .Values.proxyFrontend.containerPorts.https }}
  selector:
    app: proxy-frontend
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: {{ .Values.proxyFrontend.service.type }}
  {{- if .Values.proxyFrontend.service.sessionAffinity }}
  sessionAffinity: {{ .Values.proxyFrontend.service.sessionAffinity }}
  {{- if .Values.proxyFrontend.service.sessionAffinityConfig }}
  {{- with .Values.proxyFrontend.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if .Values.proxyFrontend.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.proxyFrontend.service.externalTrafficPolicy }}
  {{- end }}
{{- end }}
