apiVersion: v1
kind: Service
metadata:
  name: service-client
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: service-client
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  ports:
  - port: 5001
    name: service-client
    targetPort: 5001
  selector:
    app: service-client
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
