apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-socket
  namespace: {{ include "app.namespace" . | quote }}
  labels:
    app: onlyoffice-socket
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.socket.containerPorts.app }}
    name: app
    targetPort: {{ .Values.socket.containerPorts.app }}
  - port: {{ .Values.socket.containerPorts.socket }}
    name: socket
    targetPort: {{ .Values.socket.containerPorts.socket }}
  selector:
    statefulset.kubernetes.io/pod-name: socket-0
  type: ClusterIP
