{{- if and .Values.studio.enabled (eq .Values.connections.studioHost "studio") }}
apiVersion: v1
kind: Service
metadata:
  name: studio
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: studio
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  ports:
  - port: {{ .Values.studio.containerPorts.app }}
    name: app
    targetPort: {{ .Values.studio.containerPorts.app }}
  selector:
    app: studio
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  type: ClusterIP
{{- end }}
