apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-document-server
  labels:
    app: onlyoffice-document-server
spec:
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  - port: 8080
    name: spch
    targetPort: 8080
  - port: 8000
    name: docs
    targetPort: 8000
  - port: 8888
    name: prox
    targetPort: 8888
  selector:
    statefulset.kubernetes.io/pod-name: onlyoffice-document-server-0
  type: ClusterIP
