---
apiVersion: v1
kind: Service
metadata:
  name: onlyoffice-proxy
spec:
  ports:
  - port: 5050
    name: http
    targetPort: 5050
  - port: 8081
    name: url
    targetPort: 8081
  - port: 8099
    name: internal
    targetPort: 8099
  - port: 8092
    name: external
    targetPort: 8092
  selector:
    app: onlyoffice-proxy
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: onlyoffice-proxy
  labels:
    app: onlyoffice-proxy
spec:
#  securityContext:
#    runAsUser: 104
#    runAsGroup: 107
  containers:
  - name: onlyoffice-proxy
    image: onlyoffice/4testing-appserver-proxy:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: mysql-root-password
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-password
          key: mysql-password
    - name: DOCUMENT_SERVER_JWT_ENABLED
      valueFrom:
        secretKeyRef:
          name: appserver-all
          key: JWT_ENABLED
    - name: DOCUMENT_SERVER_JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: appserver-all
          key: JWT_SECRET
    - name: DOCUMENT_SERVER_JWT_HEADER
      valueFrom:
        secretKeyRef:
          name: appserver-all
          key: JWT_HEADER
    envFrom:
    - secretRef:
        name: appserver-all
    - secretRef:
        name: appserver-proxy
    ports:
    - containerPort: 5050
      name: http
    - containerPort: 8081
      name: url
    - containerPort: 8099
      name: internal
    - containerPort: 8092
      name: external
#    livenessProbe:
#      failureThreshold: 2
#      httpGet:
#        path: /
#        port: 8081
#      periodSeconds: 10
#      successThreshold: 1
#      timeoutSeconds: 5
#      initialDelaySeconds: 45
#    securityContext:
#      allowPrivilegeEscalation: false
    volumeMounts:
    - name: proxy-log
      mountPath: /var/log/nginx
  volumes:
  - name: proxy-log
    persistentVolumeClaim:
      claimName: proxy-log
