apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-data
spec:
  storageClassName: {{ .Values.persistence.filesData.storageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.filesData.size }}
