{{- if .Values.opensearch.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.opensearch.persistence.storageClass }}
  accessModes:
  {{- range .Values.opensearch.persistence.accessModes }}
  - {{ . }}
  {{- end }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.opensearch.persistence.size }}
{{- end }}
