apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: people-data
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.peopleData.size }}
