{{- if eq (include "docspace.pvc.people.create" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: people-data
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "2"
    {{- if or .Values.commonAnnotations .Values.persistence.peopleData.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.persistence.peopleData.annotations }}
    {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.peopleData.size }}
{{- end }}
