{{- if eq (include "app.pvc.proxy.create" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxy-log
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.proxyLog.size }}
{{- end }}
