{{- if eq (include "apps.pvc.router.create" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: router-log
  namespace: {{ include "apps.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "apps.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if or .Values.commonAnnotations .Values.persistence.routerLog.annotations }}
  {{- $dictValue := default .Values.commonAnnotations .Values.persistence.routerLog.annotations }}
  annotations: {{- include "apps.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.routerLog.size }}
{{- end }}
