apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: files-services
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app: files-services
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.filesServices.replicaCount }}
  selector:
    matchLabels:
      app: files-services
      {{- if .Values.commonLabels }}
      {{- include "docspace.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  serviceName: files-services
  {{- if .Values.filesServices.updateStrategy }}
  updateStrategy: {{- toYaml .Values.filesServices.updateStrategy | nindent 4 }}
  {{- end }}
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: files-services
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.filesServices.podAffinity .Values.filesServices.nodeAffinity }}
      affinity:
        {{- with .Values.filesServices.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.filesServices.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: app-wait-storage
        image: {{ .Values.initContainers.waitStorage.image.repository }}:{{ default .Values.images.tag .Values.initContainers.waitStorage.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.waitStorage.image.pullPolicy }}
        resources: {{- toYaml .Values.initContainers.waitStorage.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      {{- with .Values.initContainers.custom }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: files-services
        image: {{ .Values.filesServices.image.repository }}:{{ default .Values.images.tag .Values.filesServices.image.tag }}
        imagePullPolicy: {{ .Values.filesServices.image.pullPolicy }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.filesServices.containerPorts.app }}
          name: app
        {{- if .Values.filesServices.startupProbe.enabled }}
        startupProbe: {{- omit .Values.filesServices.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.filesServices.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.filesServices.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.filesServices.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.filesServices.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.filesServices.resources | nindent 10 }}
        env:
        - name: MYSQL_USER
          value: {{ default .Values.connections.mysqlUser .Values.filesServices.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.redis.secretName" . }}
              key: {{ .Values.connections.redisSecretKeyName }}
        - name: RABBIT_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-broker-uri
              key: broker_uri
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: docspace
        - secretRef:
            name: {{ template "docspace.coreMachineKey.secretName" . }}
        - secretRef:
            name: {{ template "docspace.jwt.secretName" . }}
        volumeMounts:
        {{- if .Values.extraConf.secretName }}
        {{- range .Values.extraConf.fileName }}
        - name: custom-file
          mountPath: /app/onlyoffice/config/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        - name: docspace-data
          mountPath: /app/onlyoffice/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
      volumes:
      {{- if .Values.extraConf.secretName }}
      - name: custom-file
        secret:
          secretName: {{ .Values.extraConf.secretName }}
      {{- end }}
      - name: docspace-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.data.name" . }}
      - name: files-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.files.name" . }}
      - name: people-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.people.name" . }}
