apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notify
  namespace: {{ include "app.namespace" . | quote }}
  labels:
    app: notify
    {{- if .Values.commonLabels }}
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify
      {{- if .Values.commonLabels }}
      {{- include "app.labels.commonLabels" . | trim | nindent 6 }}
      {{- end }}
  serviceName: notify
  {{- if .Values.notify.updateStrategy }}
  updateStrategy: {{- toYaml .Values.notify.updateStrategy | nindent 4 }}
  {{- end }}
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: notify
        {{- if .Values.commonLabels }}
        {{- include "app.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if or .Values.notify.podAffinity .Values.notify.nodeAffinity }}
      affinity:
        {{- with .Values.notify.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.notify.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: app-wait-storage
        image: {{ .Values.initContainers.waitStorage.image.repository }}:{{ default .Values.images.tag .Values.initContainers.waitStorage.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.waitStorage.image.pullPolicy }}
        resources: {{- toYaml .Values.initContainers.waitStorage.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/
      containers:
      - name: notify
        image: {{ .Values.notify.image.repository }}:{{ default .Values.images.tag .Values.notify.image.tag }}
        imagePullPolicy: {{ .Values.notify.image.pullPolicy }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.notify.containerPorts.app }}
          name: app
        {{- if .Values.notify.startupProbe.enabled }}
        startupProbe: {{- omit .Values.notify.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.notify.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.notify.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.notify.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.notify.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.notify.resources | nindent 10 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyRootPassword }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.redis.secretName" . }}
              key: {{ .Values.connections.redisSecretKeyName }}
        - name: RABBIT_URI
          value: {{ include "app.broker.uri" . | quote }}
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.jwt.secretName" . }}
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: app-all
        - secretRef: 
            name: {{ template "docspace.coreMachineKey.secretName" . }}
        - secretRef:
            name: {{ template "docspace.jwt.secretName" . }}
        volumeMounts:
        {{- if .Values.extraConf.secretName }}
        {{- range .Values.extraConf.fileName }}
        - name: custom-file
          mountPath: /app/onlyoffice/config/{{ . }}
          subPath: {{ . }}
        {{- end }}
        {{- end }}
        - name: app-data
          mountPath: /app/onlyoffice/data
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
      volumes:
      {{- if .Values.extraConf.secretName }}
      - name: custom-file
        secret:
          secretName: {{ .Values.extraConf.secretName }}
      {{- end }}
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ template "app.pvc.data.name" . }}
      - name: files-data
        persistentVolumeClaim:
          claimName: {{ template "app.pvc.files.name" . }}
      - name: people-data
        persistentVolumeClaim:
          claimName: {{ template "app.pvc.people.name" . }}
