{{- if .Values.docs.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onlyoffice-document-server
  labels:
    app: onlyoffice-document-server
spec:
  selector:
    matchLabels:
      app: onlyoffice-document-server
  serviceName: onlyoffice-document-server
  replicas: 1
  updateStrategy:
    type: {{ .Values.statefulsetUpdateStrategy.type }}
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: onlyoffice-document-server
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.docs.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.docs.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: onlyoffice-document-server
        image: {{ .Values.docs.image.repository }}:{{ .Values.docs.image.tag }}
        imagePullPolicy: {{ .Values.docs.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyRootPassword }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "app.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: DOCUMENT_SERVER_JWT_ENABLED
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_ENABLED
        - name: DOCUMENT_SERVER_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_SECRET
        - name: DOCUMENT_SERVER_JWT_HEADER
          valueFrom:
            secretKeyRef:
              name: jwt
              key: JWT_HEADER
        envFrom:
        - configMapRef:
            name: app-all
        - secretRef:
            name: jwt
        ports:
        - containerPort: {{ .Values.docs.containerPorts.http }}
          name: http
        - containerPort: {{ .Values.docs.containerPorts.https }}
          name: https
        - containerPort: {{ .Values.docs.containerPorts.spch }}
          name: spch
        - containerPort: {{ .Values.docs.containerPorts.docs }}
          name: docs
        - containerPort: {{ .Values.docs.containerPorts.proxy }}
          name: proxy
        {{- if .Values.docs.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.docs.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.docs.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.docs.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.docs.startupProbe.enabled }}
        startupProbe: {{- omit .Values.docs.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: app-data
          mountPath: /app/onlyoffice/data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ template "app.pvc.data.name" . }}
{{- end }}
