{{- if .Values.proxyFrontend.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-frontend
  labels:
    app: proxy-frontend
spec:
  selector:
    matchLabels:
      app: proxy-frontend
  serviceName: {{ template "app.svc.proxyFrontend.name" . }}
  replicas: 1
  updateStrategy:
    type: {{ .Values.statefulsetUpdateStrategy.type }}
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: proxy-frontend
      {{- if .Values.podAnnotations }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ tpl $value $ }}
        {{- end }}
      {{- end }}
    spec:
      {{- if .Values.proxyFrontend.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.proxyFrontend.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      - name: proxy-frontend
        image: {{ .Values.proxyFrontend.image.repository }}:{{ .Values.proxyFrontend.image.tag }}
        imagePullPolicy: {{ .Values.proxyFrontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyFrontend.containerPorts.http }}
          name: http
        - containerPort: {{ .Values.proxyFrontend.containerPorts.https }}
          name: https
        {{- if .Values.proxyFrontend.startupProbe.enabled }}
        startupProbe: {{- omit .Values.proxyFrontend.startupProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.proxyFrontend.readinessProbe.enabled }}
        readinessProbe: {{- omit .Values.proxyFrontend.readinessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.proxyFrontend.livenessProbe.enabled }}
        livenessProbe: {{- omit .Values.proxyFrontend.livenessProbe "enabled" | toYaml | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if .Values.proxyFrontend.extraConf.configMap }}
        - name: custom-file
          mountPath: /etc/nginx/conf.d/{{ .Values.proxyFrontend.extraConf.filename }}
          subPath: {{ .Values.proxyFrontend.extraConf.filename }}
        {{- end }}
        {{- if .Values.proxyFrontend.tls.secretName }}
        - name: tls
          mountPath: {{ .Values.proxyFrontend.tls.mountPath }}
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.proxyFrontend.extraConf.configMap }}
      - name: custom-file
        configMap:
          name: {{ .Values.proxyFrontend.extraConf.configMap }}
      {{- end }}
      {{- if .Values.proxyFrontend.tls.secretName }}
      - name: tls
        secret:
          secretName: {{ .Values.proxyFrontend.tls.secretName }}
          items:
          - key: {{ .Values.proxyFrontend.tls.crtName }}
            path: {{ .Values.proxyFrontend.tls.crtName }}
          - key: {{ .Values.proxyFrontend.tls.keyName }}
            path: {{ .Values.proxyFrontend.tls.keyName }}
      {{- end }}
{{- end }}
