apiVersion: v1
kind: Secret
metadata:
  name: appserver-proxy
type: Opaque
stringData:
  COUNT_WORKER_CONNECTIONS: "1024"
  NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".upstream"
  service_keepalive: "64"
  API_HOST: "onlyoffice-api"
  API_SYSTEM_HOST: "onlyoffice-api-system"
  CALENDAR_HOST: "onlyoffice-calendar"
  CRM_HOST: "onlyoffice-crm"
  STORAGE_ENCRYPTION_HOST: "onlyoffice-storage-encryption"
  MAIL_HOST: "onlyoffice-mail"
  STORAGE_MIGRATION_HOST: "onlyoffice-storage-migration"
  NOTIFY_HOST: "onlyoffice-notify"
  PROJECTS_SERVER_HOST: "onlyoffice-projects-server"
  URLSHORTENER_HOST: "onlyoffice-urlshortener"
  STUDIO_NOTIFY_HOST: "onlyoffice-studio-notify"
  SOCKET_HOST: "onlyoffice-socket"
  TELEGRAM_SERVICE_HOST: "onlyoffice-telegram-service"
  PEOPLE_SERVER_HOST: "onlyoffice-people-server"
  FILES_HOST: "onlyoffice-files"
  FILES_SERVICES_HOST: "onlyoffice-files-services"
  STUDIO_HOST: "onlyoffice-studio"
  BACKUP_HOST: "onlyoffice-backup"
  THUMBNAILS_HOST: "onlyoffice-thumbnails"
  SSOAUTH_HOST: "onlyoffice-ssoauth"
  DOCUMENT_SERVER: "onlyoffice-document-server"
  SERVICE_PORT: "5050"
