{{- if eq (include "app.broker.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-broker
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
type: Opaque
stringData:
  {{ .Values.connections.brokerSecretKeyName }}: {{ include "app.broker.password" . | quote }}
{{- end }}
