{{- if eq (include "docspace.broker.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-broker
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    {{- if .Values.commonAnnotations }}
    {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ .Values.connections.brokerSecretKeyName }}: {{ include "docspace.broker.password" . | quote }}
{{- end }}
