apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-broker-uri
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  broker_uri: {{ include "docspace.broker.uri" . | quote }}
