{{- if eq (include "apps.coreMachineKey.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-machine-key
  namespace: {{ include "apps.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "apps.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "apps.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  APP_CORE_MACHINEKEY: {{ include "apps.secret.coreMachineKey" . | quote }}
{{- end }}
