{{- if eq (include "docspace.coreMachineKey.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-core-machine-key
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  APP_CORE_MACHINEKEY: {{ include "docspace.secret.coreMachineKey" . | quote }}
{{- end }}
