{{- if eq (include "apps.mysql.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ include "apps.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "apps.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- if .Values.commonAnnotations }}
    {{- include "apps.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{ .Values.connections.mysqlSecretKeyPassword }}: {{ include "apps.mysql.password" . | quote }}
{{- end }}
