{{- if eq (include "docspace.jwt.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: docspace-jwt
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if typeIs "bool" .Values.jwt.enabled }}
  JWT_ENABLED: {{ .Values.jwt.enabled | quote }}
  {{- if .Values.jwt.enabled }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  JWT_HEADER: {{ .Values.jwt.header | quote }}
  JWT_IN_BODY: {{ .Values.jwt.inBody | quote }}
  {{- end }}
  {{- end }}
{{- end }}
