{{- if and (eq (include "docspace.langflow.createSecret" .) "true") .Values.langflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- $secretName := "docspace-langflow" }}
  name: {{ $secretName }}
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  LANGFLOW_SECRET_KEY: {{ include "docspace.generateSecret" (list . .Values.langflow.secret.langflowSecretKey $secretName "LANGFLOW_SECRET_KEY") | quote }}
{{- end }}