{{- if eq (include "app.mysql.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
type: Opaque
stringData:
  {{ .Values.connections.mysqlSecretKeyPassword }}: {{ include "app.mysql.password" . | quote }}
  {{ .Values.connections.mysqlSecretKeyRootPassword }}: {{ include "app.mysql.rootPassword" . | quote }}
{{- end }}
