{{- if eq (include "docspace.redis.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.connections.redisSecretKeyName }}: {{ include "docspace.redis.password" . | quote }}
{{- end }}
