{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-appserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  {{ if .Values.ingress.host }}
  - host: {{ .Values.ingress.host }}
  {{ else }}
  - host:
  {{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: onlyoffice-proxy
            port:
              number: 8092
{{ end }}
