{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docspace
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    {{- if or .Values.commonAnnotations .Values.ingress.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.ingress.annotations }}
    {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
    nginx.org/mergeable-ingress-type: "master"
    {{- if .Values.ingress.letsencrypt.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- end }}
spec:
  {{- $context := . }}
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- if not .Values.ingress.tenants }}
    - {{ .Values.ingress.host }}
    {{- else }}
    {{- range .Values.ingress.tenants }}
    - {{ . }}
    {{- end }}
    {{- end }}
    secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- if and (not .Values.ingress.host) (not .Values.ingress.tenants) }}
  - host:
  {{- else if and .Values.ingress.host (not .Values.ingress.tenants) }}
  - host: {{ .Values.ingress.host }}
  {{- end }}
  {{- if .Values.ingress.tenants }}
  {{- range .Values.ingress.tenants }}
  - host: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
