---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
stringData:
  mysql-root-password: my-secret-pw
  mysql-password: onlyoffice_pass

---
apiVersion: v1
kind: Secret
metadata:
  name: appserver-all
type: Opaque
stringData:
  MYSQL_HOST: "mysql"
  MYSQL_DATABASE: "onlyoffice"
  MYSQL_USER: "onlyoffice_user"
  APP_DOTNET_ENV: "test"
  APP_CORE_BASE_DOMAIN: "localhost"
  APP_CORE_MACHINEKEY: "your_core_machinekey"
  JWT_ENABLED: "true"
  JWT_SECRET: "jwt_secret"
  JWT_HEADER: "AuthorizationJwt"
  JWT_IN_BODY: "true"
  DOCUMENT_SERVER_URL_PUBLIC: "/ds-vpath/"
  DOCUMENT_SERVER_URL_INTERNAL: "http://onlyoffice-document-server.default.svc.cluster.local/"
  DOCUMENT_SERVER_URL_CONVERTER: "/ds-vpath/ConvertService.ashx"
  KAFKA_HOST: "onlyoffice-kafka"
  ELK_HOST: "elasticsearch-master"
  PROXY_HOST: "onlyoffice-proxy.default.svc.cluster.local"

---
apiVersion: v1
kind: Secret
metadata:
  name: appserver-proxy
type: Opaque
stringData:
  NAMESERVER: "kube-dns.kube-system.svc.cluster.local"
  SERVICE_API: "onlyoffice-api.default.svc.cluster.local:5050"
  SERVICE_API_SYSTEM: "onlyoffice-api-system.default.svc.cluster.local:5050"
  SERVICE_CALENDAR: "onlyoffice-calendar.default.svc.cluster.local:5050"
  SERVICE_CRM: "onlyoffice-crm.default.svc.cluster.local:5050"
  SERVICE_STORAGE_ENCRYPTION: "onlyoffice-storage-encryption.default.svc.cluster.local:5050"
  SERVICE_MAIL: "onlyoffice-mail.default.svc.cluster.local:5050"
  SERVICE_STORAGE_MIGRATION: "onlyoffice-storage-migration.default.svc.cluster.local:5050"
  SERVICE_NOTIFY: "onlyoffice-notify.default.svc.cluster.local:5050"
  SERVICE_PROJECTS_SERVER: "onlyoffice-projects-server.default.svc.cluster.local:5050"
  SERVICE_URLSHORTENER: "onlyoffice-urlshortener.default.svc.cluster.local:9999"
  SERVICE_STUDIO_NOTIFY: "onlyoffice-studio-notify.default.svc.cluster.local:5050"
  SERVICE_SOCKET: "onlyoffice-socket.default.svc.cluster.local:9899"
  SERVICE_TELEGRAM_SERVICE: "onlyoffice-telegram-service.default.svc.cluster.local:5050"
  SERVICE_PEOPLE_SERVER: "onlyoffice-people-server.default.svc.cluster.local:5050"
  SERVICE_FILES: "onlyoffice-files.default.svc.cluster.local:5050"
  SERVICE_FILES_SERVICES: "onlyoffice-files-services.default.svc.cluster.local:5050"
  SERVICE_STUDIO: "onlyoffice-studio.default.svc.cluster.local:5050"
  SERVICE_BACKUP: "onlyoffice-backup.default.svc.cluster.local:5050"
  SERVICE_THUMBNAILS: "onlyoffice-thumbnails.default.svc.cluster.local:9800"
  DOCUMENT_SERVER: "onlyoffice-document-server.default.svc.cluster.local"
  SERVICE_PORT: "5050"
