apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-clear-indexes
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.upgrade.job.customPodAntiAffinity .Values.upgrade.job.podAffinity .Values.upgrade.job.nodeAffinity }}
      affinity:
        {{- with .Values.upgrade.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.upgrade.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.upgrade.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.upgrade.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.upgrade.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: elasticsearch-clear-indexes
          image: mysql:8.0.36-debian
          command: ["/bin/sh", "-c"]
          args: ["/elasticsearch-clear-indexes.sh"]
          env:
            - name: ELK_SHEME
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_SHEME
            - name: ELK_HOST
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_HOST
            - name: ELK_PORT
              valueFrom:
                configMapKeyRef:
                  name: docspace
                  key: ELK_PORT
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "docspace.mysql.secretName" . }}
                  key: {{ .Values.connections.mysqlSecretKeyPassword }}
          volumeMounts:
            - name: elasticsearch-clear-indexes
              mountPath: /elasticsearch-clear-indexes.sh
              subPath: elasticsearch-clear-indexes.sh
      restartPolicy: Never
      volumes:
        - name: elasticsearch-clear-indexes
          configMap:
            name: elasticsearch-clear-indexes
            defaultMode: 0777
