{{- if .Values.identityMigration.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: identity-migration
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: identity-migration
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if or .Values.commonAnnotations .Values.identityMigration.job.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.identityMigration.job.annotations }}
    {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: identity-migration
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.identityMigration.job.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.identityMigration.job.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.identityMigration.job.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.identityMigration.job.podSecurityContext.enabled }}
      {{- $psc = .Values.identityMigration.job.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      {{- if or .Values.identityMigration.job.customPodAntiAffinity .Values.identityMigration.job.podAffinity .Values.identityMigration.job.nodeAffinity }}
      affinity:
        {{- with .Values.identityMigration.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.identityMigration.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.identityMigration.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.identityMigration.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.identityMigration.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.identityMigration.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.identityMigration.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
        - name: identity-migration
          image: {{ .Values.identityMigration.job.image.repository }}:{{ default .Values.images.tag .Values.identityMigration.job.image.tag }}
          {{- if or .Values.containerSecurityContext.enabled .Values.identityMigration.job.containerSecurityContext.enabled }}
          {{- $csc := dict }}
          {{- if .Values.identityMigration.job.containerSecurityContext.enabled }}
          {{- $csc = .Values.identityMigration.job.containerSecurityContext }}
          {{- else }}
          {{- $csc = .Values.containerSecurityContext }}
          {{- end }}
          securityContext: {{- include "docspace.securityContext" $csc | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.identityMigration.job.resources | nindent 12 }}
          env:
          - name: JDBC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "docspace.mysql.secretName" . }}
                key: {{ .Values.connections.mysqlSecretKeyPassword }}
          envFrom:
          - configMapRef:
              name: identity
      restartPolicy: Never
{{- end }}
