{{- if .Values.install.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: migration-runner
  labels:
    app:  migration-runner
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name:  migration-runner
        image: {{ .Values.install.job.image.repository }}:{{ .Values.install.job.image.tag }}
        imagePullPolicy: {{ .Values.install.job.image.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appserver.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyRootPassword }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appserver.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        envFrom:
        - configMapRef:
            name: appserver-all
      restartPolicy: Never
{{- end }}
