apiVersion: batch/v1
kind: Job
metadata:
  name: migration-runner
  labels:
    app:  migration-runner
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name:  migration-runner
        image: onlyoffice/4testing-appserver-migration-runner:develop
        ports:
        - containerPort: 5050
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-password
        envFrom:
        - configMapRef:
            name: appserver-all
