{{- if .Values.install.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{ toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name:  migration-runner
        image: {{ .Values.install.job.image.repository }}:{{ .Values.install.job.image.tag }}
        imagePullPolicy: {{ .Values.install.job.image.pullPolicy }}
        resources: {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appserver.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyRootPassword }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "appserver.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        envFrom:
        - configMapRef:
            name: appserver-all
      containers:
      - name: appserver-init-storage
        image: {{ .Values.images.initContainer.initStorage }}:{{ .Values.images.tag }}
        imagePullPolicy: IfNotPresent
        resources: {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
        {{- if .Values.onlyofficeCrm.enabled }}
        - name: crm-data
          mountPath: /var/www/products/ASC.CRM/server/
        {{- end }}
        {{- if .Values.onlyofficeProjectServer.enabled }}
        - name: project-data
          mountPath: /var/www/products/ASC.Projects/server/
        {{- end }}
        {{- if .Values.onlyofficeCalendar.enabled }}
        - name: calendar-data
          mountPath: /var/www/products/ASC.Calendar/server/
        {{- end }}
        {{- if .Values.onlyofficeMail.enabled }}
        - name: mail-data
          mountPath: /var/www/products/ASC.Mail/server/
        {{- end }}
      volumes:
      - name: files-data
        persistentVolumeClaim:
          claimName: files-data
      - name: people-data
        persistentVolumeClaim:
          claimName: people-data
      {{- if .Values.onlyofficeCrm.enabled }}
      - name: crm-data
        persistentVolumeClaim:
          claimName: crm-data
      {{- end }}
      {{- if .Values.onlyofficeProjectServer.enabled }}
      - name: project-data
        persistentVolumeClaim:
          claimName: project-data
      {{- end }}
      {{- if .Values.onlyofficeCalendar.enabled }}
      - name: calendar-data
        persistentVolumeClaim:
          claimName: calendar-data
      {{- end }}
      {{- if .Values.onlyofficeMail.enabled }}
      - name: mail-data
        persistentVolumeClaim:
          claimName: mail-data
      {{- end }}
      restartPolicy: Never
{{- end }}
