{{- if .Values.upgrade.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-upgrade
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: upgrade
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if or .Values.commonAnnotations .Values.upgrade.job.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.upgrade.job.annotations }}
    {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: upgrade
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.upgrade.job.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.upgrade.job.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.upgrade.job.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.upgrade.job.podSecurityContext.enabled }}
      {{- $psc = .Values.upgrade.job.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      {{- if or .Values.upgrade.job.customPodAntiAffinity .Values.upgrade.job.podAffinity .Values.upgrade.job.nodeAffinity }}
      affinity:
        {{- with .Values.upgrade.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.upgrade.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.upgrade.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.upgrade.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.upgrade.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.upgrade.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      initContainers:
      - name: check-db
        image: {{ .Values.initContainers.checkDB.image.repository }}:{{ .Values.initContainers.checkDB.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.checkDB.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $iccdsc := dict }}
        {{- if .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $iccdsc = .Values.upgrade.job.containerSecurityContext }}
        {{- else }}
        {{- $iccdsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $iccdsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.initContainers.checkDB.resources | nindent 10 }}
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        volumeMounts:
        - name: check-db
          mountPath: /scripts/checkdb.sh
          subPath: checkdb.sh
        command: ["/bin/sh", "-c"]
        args: ["/scripts/checkdb.sh"]
      {{- if .Values.upgrade.job.initContainers.migrationRunner.enabled }}
      - name: migration-runner
        image: {{ include "docspace.imageRepository" (list . .Values.upgrade.job.initContainers.migrationRunner.image.repository) }}:{{ default .Values.images.tag .Values.upgrade.job.initContainers.migrationRunner.image.tag }}
        imagePullPolicy: {{ .Values.upgrade.job.initContainers.migrationRunner.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $icmrsc := dict }}
        {{- if .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $icmrsc = .Values.upgrade.job.containerSecurityContext }}
        {{- else }}
        {{- $icmrsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $icmrsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.upgrade.job.initContainers.migrationRunner.resources | nindent 10 }}
        env:
        - name: MYSQL_USER
          value: {{ .Values.connections.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: MIGRATION_TYPE
          value: {{ .Values.connections.migrationType }}
        envFrom:
        - configMapRef:
            name: docspace
      {{- end }}
      {{- if .Values.upgrade.job.initContainers.identityMigration.enabled }}
      - name: identity-migration
        image: {{ include "docspace.imageRepository" (list . .Values.upgrade.job.initContainers.identityMigration.image.repository) }}:{{ default .Values.images.tag .Values.upgrade.job.initContainers.identityMigration.image.tag }}
        imagePullPolicy: {{ .Values.upgrade.job.initContainers.identityMigration.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $icmrsc := dict }}
        {{- if .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $icmrsc = .Values.upgrade.job.containerSecurityContext }}
        {{- else }}
        {{- $icmrsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $icmrsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.upgrade.job.initContainers.identityMigration.resources | nindent 10 }}
        env:
        - name: JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: mysql-root-password
        - name: JDBC_URL
          value: mysql
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: JDBC_USER_NAME
          value: root
        - name: JDBC_DATABASE
          value: {{ .Values.connections.mysqlDatabase }}
        - name: RABBIT_HOST
          value: {{ .Values.connections.brokerHost }}
        - name: REDIS_HOST
          value: {{ .Values.connections.redisHost }}  
        envFrom:
        - configMapRef:
            name: docspace
      {{- end }}
      {{- if .Values.initContainers.rootless.enabled }}
      - name: rootless
        image: {{ .Values.initContainers.rootless.image.repository }}:{{ .Values.initContainers.rootless.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.rootless.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.initContainers.rootless.containerSecurityContext.enabled }}
        {{- $icrlsc := dict }}
        {{- if .Values.initContainers.rootless.containerSecurityContext.enabled }}
        {{- $icrlsc = .Values.initContainers.rootless.containerSecurityContext }}
        {{- else }}
        {{- $icrlsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $icrlsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.initContainers.rootless.resources | nindent 10 }}
        command: ["/bin/sh", "-c"]
        args: ["chown -R 104:107  /var/docspace-data/ && chown -R 104:107  /var/router-log/"]
        volumeMounts:
        - name: docspace-data
          mountPath: /var/docspace-data
        - name: router-log
          mountPath: /var/router-log
      {{- end }}
      containers:
      - name: app-init-storage
        image: {{ include "docspace.imageRepository" (list . .Values.initContainers.initStorage.image.repository) }}:{{ default .Values.images.tag .Values.initContainers.initStorage.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.initStorage.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $csc := dict }}
        {{- if .Values.upgrade.job.containerSecurityContext.enabled }}
        {{- $csc = .Values.upgrade.job.containerSecurityContext }}
        {{- else }}
        {{- $csc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $csc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.initContainers.initStorage.resources | nindent 10 }}
        volumeMounts:
        - name: files-data
          mountPath: /var/www/products/ASC.Files/server/
        - name: people-data
          mountPath: /var/www/products/ASC.People/server/
        - name: update-scripts
          mountPath: /scripts/update.sh
          subPath: update.sh
        command: ["/bin/sh", "-c"]
        args: ["/scripts/update.sh"]
      volumes:
      - name: files-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.files.name" . }}
      - name: people-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.people.name" . }}
      - name: check-db
        configMap:
          name: check-db
          defaultMode: 0755
      - name: update-scripts
        configMap:
          name: pre-upgrade
          defaultMode: 0755
      - name: docspace-data
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.data.name" . }}
      - name: router-log
        persistentVolumeClaim:
          claimName: {{ template "docspace.pvc.router.name" . }}
      restartPolicy: Never
{{- end }}
