{{- if .Values.install.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: docspace-pre-install
  namespace: {{ include "docspace.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: install
    {{- if .Values.commonLabels }}
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if or .Values.commonAnnotations .Values.install.job.annotations }}
    {{- $dictValue := default .Values.commonAnnotations .Values.install.job.annotations }}
    {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/component: install
        {{- if .Values.commonLabels }}
        {{- include "docspace.labels.commonLabels" . | trim | nindent 8 }}
        {{- end }}
      {{- if or .Values.podAnnotations .Values.install.job.podAnnotations }}
      {{- $dictValue := default .Values.podAnnotations .Values.install.job.podAnnotations }}
      annotations: {{- include "docspace.annotations" ( dict "keyName" $dictValue "context" $ ) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "docspace.serviceAccountName" . }}
      {{- if or .Values.podSecurityContext.enabled .Values.install.job.podSecurityContext.enabled }}
      {{- $psc := dict }}
      {{- if .Values.install.job.podSecurityContext.enabled }}
      {{- $psc = .Values.install.job.podSecurityContext }}
      {{- else }}
      {{- $psc = .Values.podSecurityContext }}
      {{- end }}
      securityContext: {{- include "docspace.securityContext" $psc | nindent 8 }}
      {{- end }}
      {{- if or .Values.install.job.customPodAntiAffinity .Values.install.job.podAffinity .Values.install.job.nodeAffinity }}
      affinity:
        {{- with .Values.install.job.customPodAntiAffinity }}
        podAntiAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.install.job.podAffinity }}
        podAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.install.job.nodeAffinity }}
        nodeAffinity:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.nodeSelector .Values.install.job.nodeSelector }}
      nodeSelector: {{ toYaml (default .Values.nodeSelector .Values.install.job.nodeSelector) | nindent 8 }}
      {{- end }}
      {{- if or .Values.tolerations .Values.install.job.tolerations }}
      tolerations: {{ toYaml (default .Values.tolerations .Values.install.job.tolerations) | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      {{- if .Values.connections.hostAliases }}
      hostAliases: {{- toYaml .Values.connections.hostAliases | nindent 8 }}
      {{- end }}
      initContainers:
      - name: check-db
        image: {{ .Values.initContainers.checkDB.image.repository }}:{{ .Values.initContainers.checkDB.image.tag }}
        imagePullPolicy: {{ .Values.initContainers.checkDB.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.install.job.containerSecurityContext.enabled }}
        {{- $iccdsc := dict }}
        {{- if .Values.install.job.containerSecurityContext.enabled }}
        {{- $iccdsc = .Values.install.job.containerSecurityContext }}
        {{- else }}
        {{- $iccdsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $iccdsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.initContainers.checkDB.resources | nindent 10 }}
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        volumeMounts:
        - name: check-db
          mountPath: /scripts/checkdb.sh
          subPath: checkdb.sh
        command: ["/bin/sh", "-c"]
        args: ["/scripts/checkdb.sh"]
      {{- if .Values.install.job.initContainers.migrationRunner.enabled }}
      - name: migration-runner
        image: {{ include "docspace.imageRepository" (list . .Values.install.job.initContainers.migrationRunner.image.repository) }}:{{ default .Values.images.tag .Values.install.job.initContainers.migrationRunner.image.tag }}
        imagePullPolicy: {{ .Values.install.job.initContainers.migrationRunner.image.pullPolicy }}
        {{- if or .Values.containerSecurityContext.enabled .Values.install.job.containerSecurityContext.enabled }}
        {{- $icmrsc := dict }}
        {{- if .Values.install.job.containerSecurityContext.enabled }}
        {{- $icmrsc = .Values.install.job.containerSecurityContext }}
        {{- else }}
        {{- $icmrsc = .Values.containerSecurityContext }}
        {{- end }}
        securityContext: {{- include "docspace.securityContext" $icmrsc | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.install.job.initContainers.migrationRunner.resources | nindent 10 }}
        env:
        - name: MYSQL_USER
          value: {{ .Values.connections.mysqlUser }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "docspace.mysql.secretName" . }}
              key: {{ .Values.connections.mysqlSecretKeyPassword }}
        - name: MIGRATION_TYPE
          value: {{ .Values.connections.migrationType }}
        - name: COMMAND_TIMEOUT
          value: {{ .Values.connections.commandTimeout | quote }}
        envFrom:
        - configMapRef:
            name: docspace
      {{- end }}
      containers:
      - name: docspace-pre-install
        image: {{ .Values.initContainers.checkDB.image.repository }}:{{ .Values.initContainers.checkDB.image.tag }}
        command: ["sh", "-c", "echo Install Job completed"]
      volumes:
      - name: check-db
        configMap:
          name: check-db
          defaultMode: 0755
      restartPolicy: Never
{{- end }}
