apiVersion: v1
kind: ConfigMap
metadata:
  name: app-proxy
data:
  COUNT_WORKER_CONNECTIONS: {{ .Values.connections.countWorkerConnections | quote }}
  NGINX_ENVSUBST_TEMPLATE_SUFFIX: {{ .Values.connections.nginxSnvsubstTemplateSuffix }}
  SERVICE_API: {{ .Values.connections.apiHost }}:{{ .Values.containerPorts.app }}
  SERVICE_API_SYSTEM: {{ .Values.connections.apiSystemHost }}:{{ .Values.containerPorts.app }}
  SERVICE_NOTIFY: {{ .Values.connections.notifyHost }}:{{ .Values.containerPorts.app }}
  SERVICE_STUDIO_NOTIFY: {{ .Values.connections.studioNotifyHost }}:{{ .Values.containerPorts.app }}
  SERVICE_SOCKET: {{ .Values.connections.socketHost }}:{{ .Values.containerPorts.app }}
  SERVICE_PEOPLE_SERVER: {{ .Values.connections.peopleServerHost }}:{{ .Values.containerPorts.app }}
  SERVICE_FILES: {{ .Values.connections.filesHost }}:{{ .Values.containerPorts.app }}
  SERVICE_FILES_SERVICES: {{ .Values.connections.filesServicesHost }}:{{ .Values.containerPorts.app }}
  SERVICE_STUDIO: {{ .Values.connections.studioHost }}:{{ .Values.containerPorts.app }}
  SERVICE_BACKUP: {{ .Values.connections.backupHost }}:{{ .Values.containerPorts.app }}
  SERVICE_SSOAUTH: {{ .Values.connections.ssoauthHost }}:{{ .Values.containerPorts.app }}
  DOCUMENT_SERVER: {{ .Values.connections.documentServerHost }}
  SERVICE_CLEAR_EVENTS: {{ .Values.connections.clearEventsHost }}:{{ .Values.containerPorts.app }}
  SERVICE_DOCEDITOR: {{ .Values.connections.doceditorHost }}:{{ .Values.containerPorts.doceditor }}
  SERVICE_BACKUP_BACKGRUOND_TASKS: {{ .Values.connections.backupBackgruondTasksHost }}:{{ .Values.containerPorts.app }}
  SERVICE_LOGIN: {{ .Values.connections.loginHost }}:{{ .Values.containerPorts.login }}
