apiVersion: v1
kind: ConfigMap
metadata:
  name: app-all
  namespace: {{ include "app.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "app.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
data:
  ENV_EXTENSION: {{ .Values.connections.envExtension | quote }}
  DATABASE_MIGRATION: {{ .Values.connections.mysqlDatabaseMigration | quote }}
  MYSQL_HOST: {{ .Values.connections.mysqlHost }}
  MYSQL_DATABASE: {{ .Values.connections.mysqlDatabase }}
  MYSQL_USER: {{ .Values.connections.mysqlUser }}
  ELK_HOST: {{ .Values.connections.elkHost }}
  PROXY_HOST: {{ template "app.svc.proxy.name" . }}
  REDIS_HOST: {{ .Values.connections.redisHost }}
  REDIS_PORT: {{ .Values.connections.redisPort | quote }}
  REDIS_USER_NAME: {{ .Values.connections.redisUser }}
  RABBIT_HOST: {{ .Values.connections.brokerHost }}
  RABBIT_PORT: {{ .Values.connections.brokerPort | quote }}
  RABBIT_VIRTUAL_HOST: {{ .Values.connections.brokerVhost | quote }}
  RABBIT_USER_NAME: {{ .Values.connections.brokerUser }}
  APP_URL_PORTAL: {{ include "app.url.portal" . | quote }}
  APP_CORE_BASE_DOMAIN: {{ .Values.connections.appCoreBaseDomain | quote }}
  APP_CORE_MACHINEKEY: {{ .Values.connections.appCoreMachinekey | quote }}
  DOCUMENT_SERVER_URL_PUBLIC: {{ .Values.connections.documentServerUrlPublic | quote }}
  DOCUMENT_SERVER_URL_INTERNAL: {{ .Values.connections.documentServerUrlInternal | quote }}
  APP_KNOWN_PROXIES: {{ .Values.connections.appKnownProxies | quote }}
  APP_KNOWN_NETWORKS: {{ .Values.connections.appKnownNetworks | quote }}
