apiVersion: v1
kind: ConfigMap
metadata:
  name: check-db
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  checkdb.sh: |-
    #!/bin/bash
    mysql -h {{ .Values.connections.mysqlHost }} \
      -P {{ .Values.connections.mysqlPort }} \
      -u {{ .Values.connections.mysqlUser }} \
      -p$MYSQL_PASSWORD \
      -e "show databases;" > /dev/null
    if [ $? -ne 0 ]; then
      echo -e "\e[0;31m DB is not available \e[0m"
      exit 1
    else
      echo -e "\e[0;32m DB is available \e[0m"
    fi
