{{- if and .Values.docs.enabled .Values.upgrade.job.enabled .Values.upgrade.job.docsInitDB.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: docspace-docs-init-db
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- if .Values.commonAnnotations }}
    {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
data:
  docs_init_db.sh: |-
    #!/bin/sh
    mysql -h {{ .Values.connections.mysqlHost }} \
      -P {{ .Values.connections.mysqlPort }} \
      -u {{ .Values.connections.mysqlUser }} \
      -p$MYSQL_PASSWORD \
      -e "show databases;" > /dev/null
    if [ $? -ne 0 ]; then
      echo -e "\e[0;31m DB is not available \e[0m"
      exit 1
    else
      echo -e "\e[0;32m DB is available \e[0m"
    fi
    wget -O /scripts/createdb.sql \
      https://raw.githubusercontent.com/ONLYOFFICE/server/master/schema/mysql/createdb.sql
    mysql -h {{ .Values.connections.mysqlHost }} \
      -P {{ .Values.connections.mysqlPort }} \
      -u {{ .Values.connections.mysqlUser }} \
      -p$MYSQL_PASSWORD \
      {{ .Values.connections.mysqlDatabase }} < /scripts/createdb.sql
    if [ $? -ne 0 ]; then
      echo -e "\e[0;31m The DATABASE initialization script could not be executed \e[0m"
      exit 1
    fi
{{- end }}
