apiVersion: v1
kind: ConfigMap
metadata:
  name: remove-indexes
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  remove-indexes.sh: |
    #!/bin/bash

    apt update && apt-get install -y curl jq
    response=$(curl -s http://$ELK_HOST:{{ .Values.connections.elkPort }})
    name=$(echo $response | jq -r ".name")
    if [[ "$name" = "elasticsearch-0" ]] && [[ "$ELK_HOST" = "elasticsearch" ]]; then
      mysqlHost={{ .Values.connections.mysqlHost }}
      mysqlUser={{ .Values.connections.mysqlUser }}
      mysqlDatabase={{ .Values.connections.mysqlDatabase }}
      mysqlPort={{ .Values.connections.mysqlPort }}
      mysql -h "$mysqlHost" -P "$mysqlPort" -u "$mysqlUser" -p"$mysqlPassword" "$mysqlDatabase" -e "TRUNCATE webstudio_index;"
      curl -XDELETE http://$ELK_HOST:{{ .Values.connections.elkPort }}/files_folder
      curl -XDELETE http://$ELK_HOST:{{ .Values.connections.elkPort }}/files_file
    fi
