apiVersion: v1
kind: ConfigMap
metadata:
  name: remove-indexes
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  remove-indexes.sh: |
    #!/bin/bash

    apt update && apt-get install -y curl jq
    response=$(curl -s http://$ELK_HOST:{{ .Values.connections.elkPort }})
    name=$(echo $response | jq -r ".name")
    if [[ "$name" = "elasticsearch-0" ]] && [[ "$ELK_HOST" = "elasticsearch" ]]; then
      echo "name"
      echo $name

      echo "mysqlHost"
      mysqlHost={{ .Values.connections.mysqlHost }}
      echo $mysqlHost

      echo "mysqlUser"
      mysqlUser={{ .Values.connections.mysqlUser }}
      echo $mysqlUser

      echo "mysqlPassword"
      echo $mysqlPassword
      mysqlDatabase=docspace
      mysql -h "${MYSQL_HOST:-$mysqlHost}" -P "${MYSQL_PORT:-3306}" -u "$mysqlUser" -p"$mysqlPassword" "$mysqlDatabase" -e "SELECT * FROM webstudio_index;"
      mysql -h "${MYSQL_HOST:-$mysqlHost}" -P "${MYSQL_PORT:-3306}" -u "$mysqlUser" -p"$mysqlPassword" "$mysqlDatabase" -e "TRUNCATE webstudio_index;"
      echo "XDELETE files_folder"
      curl -XDELETE http://$ELK_HOST:{{ .Values.connections.elkPort }}/files_folder
      echo "XDELETE files_file"
      curl -XDELETE http://$ELK_HOST:{{ .Values.connections.elkPort }}/files_file
      echo "finish"
    fi
