{{- if .Values.identity.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    {{- if .Values.commonAnnotations }}
    {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
data:
  JDBC_URL: {{ printf "%s:%s" .Values.connections.mysqlHost .Values.connections.mysqlPort | quote }}
  JDBC_DATABASE: {{ .Values.connections.mysqlDatabase | quote }}
  REDIS_HOST: {{ .Values.connections.redisHost | quote }}
  REDIS_USERNAME: {{ .Values.connections.redisUser | quote }}
  REDIS_PORT: {{ .Values.connections.redisPort | quote }}
  REDIS_DB: {{ .Values.connections.redisDB | quote }}
  SPRING_APPLICATION_NAME: {{ .Values.identity.identityAuthorization.env.springApplicationName | quote }}
  SPRING_APPLICATION_NAME_API: {{ .Values.identity.identityAuthorization.env.springApplicationName | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.identity.env.springProfilesActive | quote }}
{{- end }}
