{{- if .Values.identity.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    {{- if .Values.commonAnnotations }}
    {{- include "docspace.annotations" ( dict "keyName" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
data:
  JDBC_URL: {{ .Values.connections.mysqlHost | quote  }}
  JDBC_DATABASE: {{ .Values.connections.mysqlDatabase | quote }}
  REDIS_HOST: {{ .Values.connections.redisHost | quote }}
  REDIS_USERNAME: {{ .Values.connections.redisUser | quote }}
  REDIS_PORT: {{ .Values.connections.redisPort | quote }}
  REDIS_DB: {{ .Values.connections.redisDB | quote }}
  SERVER_PORT_IDENTITY: "ASC.Identity.Authorization"
  SERVER_PORT_IDENTITY_API: "ASC.Identity.Registration"
  SPRING_PROFILES_ACTIVE: "dev"
{{- end }}
