apiVersion: v1
kind: ConfigMap
metadata:
  name: pre-upgrade
  namespace: {{ include "docspace.namespace" . | quote }}
  {{- if .Values.commonLabels }}
  labels:
    {{- include "docspace.labels.commonLabels" . | trim | nindent 4 }}
  {{- end }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  update.sh: |-
    #!/bin/bash
    mysql -h {{ .Values.connections.mysqlHost }} \
      -u {{ .Values.connections.mysqlUser }} \
      -p$MYSQL_PASSWORD \
      -e "show databases;" > /dev/null
    if [ $? -ne 0 ]; then
      echo -e "\e[0;31m DB is not available \e[0m"
      exit 1
    fi
    rm -rf /var/www/products/ASC.Files/server/*
    rm -rf /var/www/products/ASC.People/server/*
    # mysql -h mysql -u root -p$MYSQL_PASSWORD onlyoffice < /sql/changedb.sql
    echo work done
