{{- if .Values.proxyFrontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-conf
data:
  default.conf: |-
    map $http_host $this_host {
      "" $host;
      default $http_host;
    }

    map $http_x_forwarded_proto $the_scheme {
      #default $http_x_forwarded_proto;
      default https;
      #"" $scheme;
      "" https;
    }

    map $http_x_forwarded_host $the_host {
      default $http_x_forwarded_host;
      #default {{ .Values.proxyFrontend.hostname }};
      "" $this_host;
      #"" {{ .Values.proxyFrontend.hostname }};
    }

    map $http_upgrade $proxy_connection {
      default upgrade;
      "" close;
    }

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $proxy_connection;
    proxy_set_header X-Forwarded-Host $the_host;
    proxy_set_header X-Forwarded-Proto $the_scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-REWRITER-URL $the_scheme://$the_host;
    proxy_set_header Host $the_host;
    server {
       listen 80;
       listen [::]:80;
       server_name {{ .Values.proxyFrontend.hostname }};
       return 301 https://$host$request_uri;

    }

    server {
      listen 0.0.0.0:443 ssl http2;
      listen [::]:443 ssl http2;
      server_name {{ .Values.proxyFrontend.hostname }};
      server_tokens off;
      client_max_body_size    4G;
      dav_methods PUT DELETE MKCOL COPY MOVE;

      gzip             on;
      gzip_comp_level  6;
      gzip_min_length  100;
      gzip_buffers 16 8k;
      gzip_proxied     any;
      gzip_types       application/x-javascript application/javascript text/css application/xml application/json image/svg+xml;

     # root /usr/share/nginx/html;

      ssl_certificate {{ .Values.proxyFrontend.tls.mountPath }}/{{ .Values.proxyFrontend.tls.crtName }};
      ssl_certificate_key {{ .Values.proxyFrontend.tls.mountPath }}/{{ .Values.proxyFrontend.tls.keyName }};
      ssl_verify_client off;

      ssl_session_cache shared:MozSSL:10m;   # 40000 sessions
      ssl_session_timeout 1d;
      ssl_session_tickets off;
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
      ssl_prefer_server_ciphers off;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";


    location / {

            proxy_pass http://proxy:8092;
        }
    }
{{- end }}
