apiVersion: v1
kind: ConfigMap
metadata:
  name: change-hosts
data:
  change-hosts.sh: |-
    #!/bin/bash
    cp /etc/hosts ~/hosts.new
    sed -i '/^::1/s/^/#/' ~/hosts.new
    cp -f ~/hosts.new /etc/hosts
