apiVersion: v1
kind: ConfigMap
metadata:
  name: remove-indexes
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
data:
  remove-indexes.sh: |
    #!/bin/bash

    apt update && apt-get install -y curl jq
    response=$(curl -s http://$ELK_HOST:$ELK_PORT
    name=$(echo $response | jq -r ".name")
    if [[ "$name" = "elasticsearch-0" ]] && [[ "$ELK_HOST" = "elasticsearch" ]]; then
      mysql \
      -h {{ .Values.connections.mysqlHost }} \
      -P {{ .Values.connections.mysqlPort }} \
      -u {{ .Values.connections.mysqlUser }} \
      -p"$mysqlPassword" {{ .Values.connections.mysqlDatabase }} \
      -e "TRUNCATE webstudio_index;"
      curl -XDELETE http://$ELK_HOST:$ELK_PORT/files_folder
      curl -XDELETE http://$ELK_HOST:$ELK_PORT/files_file
    fi
