name: lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - '**/README.md'
      - '**/CHANGELOG.md'
      - '**/LICENSE'

jobs:
  lint-chart:           
    name: lint chart ${{ github.event.repository.name }}
    uses: ONLYOFFICE/ga-common/.github/workflows/helm-lint.yaml@master
    with: 
      ct_version: 3.8.0
      enable_yaml_lint: true
      enable_kube_lint: true

  validate-manifests:
    name: "k8s manifests api validation"
    uses: ONLYOFFICE/ga-common/.github/workflows/deprecated-recources.yaml@master
    with:
      manual_k8s: ${{ github.event.inputs.kubernetes_version }}
      set_keys: |
              "--set serviceAccount.create=true \
               --set healthchecks.enabled=true \
               --set ingress.enabled=true \
               --set install.job.enabled=true \
               --set elasticsearch.enabled=true \
               --set serviceAccount.create=true"
