---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
type: Opaque
stringData:
  mysql-root-password: my-secret-pw
  mysql-password: onlyoffice_pass

---
apiVersion: v1
kind: Secret
metadata:
  name: appserver-all
type: Opaque
stringData:
  MYSQL_HOST: "mysql"
  MYSQL_DATABASE: "onlyoffice"
  MYSQL_USER: "onlyoffice_user"
  APP_DOTNET_ENV: "test"
  APP_CORE_BASE_DOMAIN: "localhost"
  APP_CORE_MACHINEKEY: "your_core_machinekey"
  JWT_ENABLED: "true"
  JWT_SECRET: "jwt_secret"
  JWT_HEADER: "AuthorizationJwt"
  JWT_IN_BODY: "true"
  DOCUMENT_SERVER_URL_PUBLIC: "/ds-vpath/"
  DOCUMENT_SERVER_URL_INTERNAL: "http://onlyoffice-document-server/"
  DOCUMENT_SERVER_URL_CONVERTER: "/ds-vpath/ConvertService.ashx"
  KAFKA_HOST: "onlyoffice-kafka"
  ELK_HOST: "elasticsearch-master"
  PROXY_HOST: "onlyoffice-proxy"

---
apiVersion: v1
kind: Secret
metadata:
  name: appserver-proxy
type: Opaque
stringData:
  COUNT_WORKER_CONNECTIONS: "1024"
  NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".upstream"
  service_keepalive: "64"
  API_HOST: "onlyoffice-api"
  API_SYSTEM_HOST: "onlyoffice-api-system"
  CALENDAR_HOST: "onlyoffice-calendar"
  CRM_HOST: "onlyoffice-crm"
  STORAGE_ENCRYPTION_HOST: "onlyoffice-storage-encryption"
  MAIL_HOST: "onlyoffice-mail"
  STORAGE_MIGRATION_HOST: "onlyoffice-storage-migration"
  NOTIFY_HOST: "onlyoffice-notify"
  PROJECTS_SERVER_HOST: "onlyoffice-projects-server"
  URLSHORTENER_HOST: "onlyoffice-urlshortener"
  STUDIO_NOTIFY_HOST: "onlyoffice-studio-notify"
  SOCKET_HOST: "onlyoffice-socket"
  TELEGRAM_SERVICE_HOST: "onlyoffice-telegram-service"
  PEOPLE_SERVER_HOST: "onlyoffice-people-server"
  FILES_HOST: "onlyoffice-files"
  FILES_SERVICES_HOST: "onlyoffice-files-services"
  STUDIO_HOST: "onlyoffice-studio"
  BACKUP_HOST: "onlyoffice-backup"
  THUMBNAILS_HOST: "onlyoffice-thumbnails"
  SSOAUTH_HOST: "onlyoffice-ssoauth"
  DOCUMENT_SERVER: "onlyoffice-document-server"
  SERVICE_PORT: "5050"
